//! One classifier, one truth (SELF-POLLUTION-1 §2.1): is a path rmap's OWN
//! `rmap map` exhaust (per-directory / per-file `MAP.md` sidecars, the `.rgr/`
//! tool-state dir), or OS-generated noise (`.DS_Store` and kin)?
//!
//! ## Why this module exists (abstraction one-liner)
//!
//! - **what:** the single `is_self_generated` / `is_os_noise` predicate pair.
//! - **concrete current users:** (1) doc inventory (`discover_doc_inventory`) —
//!   so a generated map is flagged and excludable; (2) INDEX_DRIFT
//!   (`daemon-runtime::index_drift`) — so rmap's own sidecars do not inflate the
//!   changed-files count; (3) the seed corpus pass
//!   (`daemon-runtime::seed_pass`) — so exhaust is not embedded. All three reach
//!   it through `doc-facts`, a zero-dependency leaf crate the daemon already
//!   depends on.
//! - **axis of variation:** none yet — this is a *shared pure predicate*, not a
//!   dispatch point. It lives in one place precisely so the three surfaces can
//!   never diverge on what "rmap's own exhaust" means.
//! - **rejected simpler alternative:** duplicating the name-glob + marker check at
//!   each of the three call sites (the exact drift-that-audit-found — three
//!   surfaces, three subtly different notions of "generated").
//!
//! ## Detection is evidence-based, never a bare name (honesty rule)
//!
//! The `rmap map` generator writes a first-line HTML-comment marker
//! ([`GENERATED_MARKER`]) into every sidecar. A file whose NAME matches the
//! sidecar convention is treated as self-generated ONLY when that marker confirms
//! it: a user's own hand-authored `MAP.md` (a name collision) carries no marker
//! and is NOT excluded. The name convention only *gates* the marker read so the
//! (potentially hot) content read is bounded to candidates — never the whole tree.
//!
//! The two exceptions that classify by name alone are definitional, not
//! heuristic: the `.rgr/` directory is rmap's own state root (no user artifact
//! lives there and no marker exists to read), and OS-noise filenames
//! (`.DS_Store`) have no content contract at all. Both are recorded as such.

/// The exact first-line marker `rmap map` writes into every generated sidecar
/// (`crates/rgr/src/presentation/map.rs`). Matched as a prefix because the full
/// line embeds a snapshot id: `<!-- generated by rmap map from snapshot …; do not
/// hand-edit -->`.
pub const GENERATED_MARKER: &str = "<!-- generated by rmap map";

/// The final path component (basename) of a forward-slash relative path.
fn file_name(rel_path: &str) -> &str {
    rel_path.rsplit('/').next().unwrap_or(rel_path)
}

/// Does `rel_path`'s basename match the `rmap map` sidecar naming convention
/// (`MAP.md`, `<base>_<ext>_MAP.md`, `<base>__MAP.md`)? NAME ONLY — a match is a
/// *candidate*; [`GENERATED_MARKER`] is the evidence that confirms generation.
/// Exposed so hot paths (drift, seed) can gate the marker read to candidates.
pub fn has_map_sidecar_name(rel_path: &str) -> bool {
    let name = file_name(rel_path);
    name == "MAP.md" || name.ends_with("_MAP.md")
}

/// Is `rel_path` inside rmap's own `.rgr/` tool-state directory? Definitional: no
/// user artifact lives there, and there is no marker to read.
///
/// Restricted to the REPOSITORY-ROOT `.rgr` (`.rgr` itself or `.rgr/…`): `rmap map`
/// and the warm-cache writers only ever create `<repo_root>/.rgr/…` (see
/// `daemon-runtime::livegraph_warm_cache::partition_cache_path`). A `.rgr` component
/// NESTED deeper in the tree is NOT rmap's own state — it is a reader-owned path we
/// have no evidence about — so excluding it would silently drop a real reader change
/// from drift/docs/seed (honesty rule: no classification from a bare name where the
/// definitional guarantee does not hold). review-4 finding 1.
pub fn is_tool_state_path(rel_path: &str) -> bool {
    rel_path == ".rgr" || rel_path.starts_with(".rgr/")
}

/// Is `rel_path` rmap's OWN generated exhaust — a `rmap map` sidecar (confirmed by
/// the first-line marker) or a file under `.rgr/`?
///
/// `first_line` is the file's first line when it could be read, `None` when it
/// was not read or was unreadable. A sidecar-NAMED file is excluded ONLY when
/// `first_line` positively carries [`GENERATED_MARKER`]: a marker-less `MAP.md`
/// (a user's own doc, or a file we could not read) is NOT self-generated — we
/// never classify from a bare name (honesty rule).
pub fn is_self_generated(rel_path: &str, first_line: Option<&str>) -> bool {
    if is_tool_state_path(rel_path) {
        return true;
    }
    if has_map_sidecar_name(rel_path) {
        return matches!(first_line, Some(l) if l.trim_start().starts_with(GENERATED_MARKER));
    }
    false
}

/// Is `rel_path` OS-generated noise that is never the reader's change
/// (`.DS_Store`, `Thumbs.db`, `desktop.ini`)? Name-based: these have no content
/// contract. Kept deliberately narrow — this is the `.DS_Store`-class noise the
/// slice names, not a general ignore engine.
pub fn is_os_noise(rel_path: &str) -> bool {
    matches!(
        file_name(rel_path),
        ".DS_Store" | "Thumbs.db" | "desktop.ini"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const MARKER_LINE: &str =
        "<!-- generated by rmap map from snapshot snap-abcdef0; do not hand-edit -->";

    #[test]
    fn map_sidecar_names_recognized() {
        assert!(has_map_sidecar_name("MAP.md"));
        assert!(has_map_sidecar_name("src/core/MAP.md"));
        assert!(has_map_sidecar_name("src/generator_ts_MAP.md"));
        assert!(has_map_sidecar_name("Makefile__MAP.md"));
        // Not a sidecar name.
        assert!(!has_map_sidecar_name("README.md"));
        assert!(!has_map_sidecar_name("docs/SITEMAP.md"));
    }

    #[test]
    fn marker_confirms_generated() {
        assert!(is_self_generated("src/core/MAP.md", Some(MARKER_LINE)));
        assert!(is_self_generated(
            "src/generator_ts_MAP.md",
            Some(MARKER_LINE)
        ));
    }

    #[test]
    fn markerless_user_map_is_not_self_generated() {
        // Name collision: a human authored a MAP.md with no rmap marker. Honesty
        // rule — a bare name is not evidence, so it is NOT excluded.
        assert!(!is_self_generated(
            "src/core/MAP.md",
            Some("# Core module\n")
        ));
        // Unread content (None) is also not evidence of generation.
        assert!(!is_self_generated("src/core/MAP.md", None));
    }

    #[test]
    fn non_sidecar_never_self_generated_regardless_of_line() {
        assert!(!is_self_generated("README.md", Some(MARKER_LINE)));
    }

    #[test]
    fn root_tool_state_dir_is_self_generated_without_marker() {
        // rmap writes `<repo_root>/.rgr/…` only — the ROOT `.rgr` is definitional.
        assert!(is_self_generated(".rgr", None));
        assert!(is_self_generated(".rgr/state.json", None));
        assert!(is_self_generated(".rgr/warm-cache/p.cache", None));
    }

    #[test]
    fn nested_rgr_is_not_tool_state() {
        // review-4 finding 1: a `.rgr` component nested below the root is a
        // reader-owned path, not rmap's state root. We have no evidence it is our
        // exhaust, so it must NOT be excluded from drift/docs/seed (honesty rule).
        assert!(!is_tool_state_path("nested/.rgr/x"));
        assert!(!is_self_generated("nested/.rgr/x", None));
        assert!(!is_tool_state_path("a/b/.rgr"));
        assert!(!is_tool_state_path("rgr/x")); // no leading dot → not our dir
        assert!(!is_tool_state_path("src/.rgrconfig")); // prefix, not the dir
    }

    #[test]
    fn os_noise_recognized_by_name() {
        assert!(is_os_noise(".DS_Store"));
        assert!(is_os_noise("a/b/.DS_Store"));
        assert!(is_os_noise("Thumbs.db"));
        assert!(!is_os_noise("README.md"));
    }
}
