//! Index-time "is this file generated?" content sniff (RG-REQ-001-L08).
//!
//! A pure function of a file's first eight lines over a FROZEN, case-sensitive
//! marker list. It is deliberately narrow: it flags only files that carry an
//! explicit machine-authored banner, and never a hand-written file that merely
//! mentions code generation in prose.
//!
//! The markers were calibrated on the analyzed corpora (COMPLEXITY-SCOPE-1 §2.1.1):
//! tree-sitter's `parser.c` (`Automatically @generated`), a Bison parser
//! (`A Bison parser, made by GNU Bison`), a wrangler type file (`DO NOT EDIT`),
//! and the generic `@generated` convention. The earlier candidate `generated by`
//! was DROPPED because it flags the hand-written leveldb `table/block.cc`
//! (`// Decodes the blocks generated by block_builder.cc.`) — the list is narrowed
//! on a false positive, never widened by guesswork (§4 stop condition).
//!
//! This file must itself stay unflagged when the product indexes its own source
//! (CS-C14 asserts 0 generated files on the candidate tree): the marker literals
//! live below this doc comment and inside the test module, never within the first
//! eight lines of the file head.

/// The number of leading lines the sniff inspects. A marker on line 9 or beyond
/// is not a banner — a generated file declares itself at the very top.
const HEAD_LINES: usize = 8;

/// FROZEN, case-sensitive generated-file markers. Order is irrelevant (any hit
/// flags the file). Changing this list is a DECISION_REQUIRED (§4): it may be
/// narrowed on a demonstrated false positive but never widened by guesswork.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Automatically generated",
    "DO NOT EDIT",
    "made by GNU Bison",
];

/// True iff one of the [`GENERATED_MARKERS`] occurs within the first
/// [`HEAD_LINES`] lines of `content`. Pure and content-only — the same bytes
/// always yield the same answer (RG-REQ-001-L09), so the flag survives a
/// no-change refresh unchanged.
pub fn is_generated_content(content: &str) -> bool {
    content
        .lines()
        .take(HEAD_LINES)
        .any(|line| GENERATED_MARKERS.iter().any(|marker| line.contains(marker)))
}

#[cfg(test)]
mod tests {
    use super::is_generated_content;

    #[test]
    fn generated_marker_within_first_eight_lines_is_generated() {
        // Each frozen marker, placed on line 1 and on line 8 — both inside the window.
        let line1 = [
            "/* Automatically @generated by tree-sitter v0.25.10 */",
            "/* A Bison parser, made by GNU Bison 3.8.2.  */",
            "// Generated by wrangler. DO NOT EDIT.",
        ];
        for head in line1 {
            assert!(
                is_generated_content(&format!("{head}\nreal code here\n")),
                "marker on line 1 should flag: {head}"
            );
        }
        // A marker that first appears on line 8 is still within the window.
        let mut body = String::new();
        for _ in 0..7 {
            body.push_str("// ordinary header line\n");
        }
        body.push_str("// Automatically generated — do not touch\n");
        assert!(is_generated_content(&body), "marker on line 8 should flag");
    }

    #[test]
    fn marker_beyond_the_eighth_line_is_not_generated() {
        // The `@generated` marker only on line 9 — outside the window.
        let mut body = String::new();
        for _ in 0..8 {
            body.push_str("// ordinary header line\n");
        }
        body.push_str("// @generated late\n");
        assert!(
            !is_generated_content(&body),
            "marker on line 9 must not flag"
        );
    }

    #[test]
    fn hand_written_body_mentioning_generated_is_not_generated() {
        // leveldb table/block.cc:5 — the narrowing witness. `generated by` was
        // dropped from the marker list precisely so this hand-written header stays
        // unflagged.
        let block_cc = "\
// Copyright (c) 2011 The LevelDB Authors. All rights reserved.\n\
// Use of this source code is governed by a BSD-style license that can be\n\
// found in the LICENSE file. See the AUTHORS file for names of contributors.\n\
//\n\
// Decodes the blocks generated by block_builder.cc.\n\
\n\
#include \"table/block.h\"\n";
        assert!(
            !is_generated_content(block_cc),
            "a hand-written header mentioning generation must not flag"
        );
    }

    #[test]
    fn empty_content_is_not_generated() {
        assert!(!is_generated_content(""));
    }
}
