//! Unit tests for `seed_pass.rs` (the background embed pass + coordinator). Split
//! out via `#[path]` (the repo idiom, e.g. `pass_tests.rs`) so `seed_pass.rs` stays
//! under the 500-line guardrail (review-6 #2). Child module of `seed_pass`;
//! `super::*` = the pass + coordinator under test.

use super::*;

#[test]
fn seed_excludes_exhaust_and_env_but_keeps_marker_less_and_source() {
    // SELF-POLLUTION-1 §2.4: rmap's own marker-confirmed `map` sidecars, `.rgr/`, and
    // `.env*` are NOT embedded; a user's marker-less MAP.md and real source ARE.
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    let write = |rel: &str, body: &str| {
        let p = root.join(rel);
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(p, body).unwrap();
    };
    write(
        "src/MAP.md",
        "<!-- generated by rmap map from snapshot snap-0; do not hand-edit -->\n",
    );
    write("docs/MAP.md", "# hand-authored\n");

    // Generated sidecar → excluded (marker).
    assert!(seed_path_is_exhaust(root, "src/MAP.md"));
    // `.env*` → excluded (name rule, no read).
    assert!(seed_path_is_exhaust(root, ".env"));
    assert!(seed_path_is_exhaust(root, "config/.env.production"));
    // ROOT `.rgr/` → excluded (definitional).
    assert!(seed_path_is_exhaust(root, ".rgr/state.json"));
    // review-4 finding 1: a NESTED `.rgr` is NOT rmap's state root → KEPT for
    // embedding (conservative: never silently dropped as exhaust without evidence).
    assert!(!seed_path_is_exhaust(root, "sub/.rgr/state.json"));
    // Marker-less user MAP.md → NOT excluded (honesty).
    assert!(!seed_path_is_exhaust(root, "docs/MAP.md"));
    // Real source → NOT excluded.
    assert!(!seed_path_is_exhaust(root, "src/lib.rs"));
}

#[test]
fn seed_keeps_unreadable_and_absent_sidecars_never_asserts_exhaust_from_failed_read() {
    // review-5 finding 3 / operator RULING 3: a sidecar-NAMED corpus path we cannot
    // READ must NOT be asserted exhaust from the failed read — it is KEPT for embedding
    // (conservative). NotFound (gone) and unreadable (permission/IO) are both kept, but
    // kept DISTINCT in the code (no silent `.ok()` collapse).
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();

    // A directory named like a sidecar: exists but `read_to_string` errors non-NotFound.
    std::fs::create_dir_all(root.join("blocked/MAP.md")).unwrap();

    // Unreadable (a directory at the path) → UNKNOWN → KEPT (not exhaust).
    assert!(!seed_path_is_exhaust(root, "blocked/MAP.md"));
    // NotFound (never created) → gone → KEPT (not exhaust).
    assert!(!seed_path_is_exhaust(root, "gone/MAP.md"));
}

#[test]
fn generation_supersede_is_per_repo_and_monotonic() {
    let c = SeedCoordinator::new();
    assert_eq!(c.current_generation("r1"), 0);
    let g1 = c.bump_generation("r1");
    let g2 = c.bump_generation("r1");
    assert!(g2 > g1, "a newer trigger supersedes the older generation");
    assert_eq!(c.current_generation("r1"), g2);
    // Independent per repo — one repo's bump never advances another's.
    assert_eq!(c.current_generation("r2"), 0);
}

/// review-5 #2 regression (SEED-CHUNK-1 SQLite form) — the forget-vs-seed
/// publication race is closed DETERMINISTICALLY (no detached thread / no model): an
/// in-flight pass that built its vectors BEFORE a concurrent `forget` completed must
/// NOT write `seed_vectors` for a now-forgotten repo. The gate is `publish_guarded`'s
/// registry recheck under the DB write slot — exactly the code the real pass runs.
#[test]
fn publish_is_skipped_after_forget_removes_the_registry_entry() {
    use repo_graph_seed::{SeedCorpusRead, SeedVectorEntry};
    use repo_graph_storage::StorageConnection;

    let root = tempfile::tempdir().expect("state root");
    let registry = crate::registry::RepoRegistry::with_state_root(root.path()).expect("registry");
    let state = Arc::new(DaemonState::with_registry(registry));

    // Register a repo — allocates repo_uid + db_path under <root>/databases/.
    let repo_dir = root.path().join("repo");
    std::fs::create_dir_all(&repo_dir).unwrap();
    let (repo_uid, db_path, canonical_path) = {
        let mut reg = state.registry_mut();
        let e = reg.register(&repo_dir).expect("register").clone();
        (e.repo_uid, e.db_path, e.canonical_path)
    };

    // Materialize a real DB with a READY snapshot so the SQLite publish FKs resolve.
    // (migrations via StorageConnection::open; the repo+snapshot rows via a raw conn —
    // rusqlite is a dev-dep sharing the same bundled libsqlite3.)
    StorageConnection::open(&db_path).expect("create db + migrations");
    {
        let conn = rusqlite::Connection::open(&db_path).expect("raw open");
        conn.execute(
            "INSERT INTO repos (repo_uid, name, root_path, created_at) VALUES (?,?,?,?)",
            rusqlite::params![repo_uid, "repo", "/repo", "2026-01-01T00:00:00Z"],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO snapshots (snapshot_uid, repo_uid, kind, status, created_at) \
             VALUES ('s1', ?, 'full', 'ready', '2026-01-01T00:00:00Z')",
            rusqlite::params![repo_uid],
        )
        .unwrap();
    }

    let repo_state = state.load_repo(&db_path, &repo_uid).expect("load repo");
    let generation = state.seed_coord().bump_generation(&repo_uid);
    let entry = SeedVectorEntry {
        node_uid: "n1".to_string(),
        stable_key: format!("{repo_uid}:a.rs#f:SYMBOL"),
        file_uid: "fu1".to_string(),
        path: "a.rs".to_string(),
        line: Some(1),
        qualified_name: Some("f".to_string()),
        is_test: false,
        is_decl: false,
        content_hash: "h1".to_string(),
        // The publish stamps the row's `dim` = `MODEL_DIM`, and the homogeneity-
        // validating read now rejects a vector whose length ≠ `dim` — so this test
        // vector must be `MODEL_DIM`-long to be a well-formed row (the race, not a
        // corrupt store, is what's under test).
        vector: vec![0.0f32; crate::seed::MODEL_DIM],
    };

    // (1) A pass publishing for a STILL-REGISTERED repo writes the vectors.
    let out = publish_guarded(
        &state,
        &repo_state,
        &db_path,
        &repo_uid,
        generation,
        "s1",
        "sha256:test",
        std::slice::from_ref(&entry),
    );
    assert!(
        matches!(out, PublishOutcome::Published),
        "a registered repo publishes, got {out:?}"
    );
    let stored = StorageConnection::open(&db_path)
        .unwrap()
        .read_seed_vectors("s1")
        .unwrap();
    assert_eq!(
        stored.entries.len(),
        1,
        "vectors present after a valid publish"
    );

    // (2) `forget` removes the registry entry (WITHOUT bumping the seed generation —
    //     forget is not an index).
    state
        .registry_mut()
        .remove(&canonical_path)
        .expect("forget removes the registry entry");

    // (3) The late in-flight pass — SAME generation — attempts to publish. The
    //     registry recheck must fire and SKIP before writing: no orphan resurrected.
    let out2 = publish_guarded(
        &state,
        &repo_state,
        &db_path,
        &repo_uid,
        generation,
        "s1",
        "sha256:test",
        std::slice::from_ref(&entry),
    );
    match out2 {
        PublishOutcome::Skipped(reason) => assert!(
            reason.contains("forgotten"),
            "skip names the forget cause: {reason}"
        ),
        other => panic!("a forgotten repo must skip publish, got {other:?}"),
    }
    let after = StorageConnection::open(&db_path)
        .unwrap()
        .read_seed_vectors("s1")
        .unwrap();
    assert_eq!(
        after.entries.len(),
        1,
        "the forget-vs-seed race is closed: the skipped pass wrote no new vectors"
    );
}

#[test]
fn self_heal_reseed_latch_is_idempotent_and_reclaimable() {
    // SEED-CHUNK-2 §2.4: the self-heal trigger must spawn at most ONE re-seed per db while
    // one is in flight (so repeated stale reads neither livelock nor pile up threads), and
    // must re-arm once that pass terminates (a still-stale store can re-trigger later).
    let c = SeedCoordinator::new();
    let db = Path::new("/x/databases/abcd1234.db");

    // First stale read claims the latch → THIS caller spawns the heal.
    assert!(
        c.mark_reseed_scheduled(db),
        "the first stale read claims the latch and is responsible for spawning the re-seed"
    );
    // Further stale reads while it is in flight do NOT re-claim → no duplicate passes.
    assert!(
        !c.mark_reseed_scheduled(db),
        "a second stale read must NOT re-claim while a heal is already scheduled/in flight"
    );
    assert!(!c.mark_reseed_scheduled(db), "…and neither does a third");

    // The pass terminates → latch released → a later stale read can re-trigger.
    c.clear_reseed_scheduled(db);
    assert!(
        c.mark_reseed_scheduled(db),
        "after the pass ends the latch re-arms so a still-stale store re-triggers"
    );

    // Independent per db — one db's latch never blocks another's heal.
    let other = Path::new("/x/databases/ef567890.db");
    assert!(
        c.mark_reseed_scheduled(other),
        "a different db latches independently"
    );
}

#[test]
fn running_registration_is_doctor_visible_and_cancellable() {
    let c = SeedCoordinator::new();
    let db = Path::new("/x/databases/abcd1234.db");
    assert!(!c.is_running_for_db(db), "no pass registered yet");

    let (guard, flag) = c.register_running(db);
    assert!(
        c.is_running_for_db(db),
        "a registered pass is doctor-visible (building)"
    );
    assert!(!flag.is_cancelled());

    // A newer index cancels the in-flight pass via its db_path.
    c.request_cancel_for_db(db);
    assert!(
        flag.is_cancelled(),
        "request_cancel_for_db fires the pass's cancel flag"
    );

    drop(guard);
    assert!(
        !c.is_running_for_db(db),
        "the RunningGuard deregisters on drop — no stale 'building' after the pass ends"
    );
}

// review-10 #3: a cancel issued BEFORE a pass registers is lost (no flag exists to
// set) — the premise for the post-register generation re-check in `attempt_seed`.
// This pins the coordinator semantics the re-check compensates for: cancel-before-
// register does NOT reach the later flag; cancel-after-register does.
#[test]
fn cancel_before_register_is_lost_cancel_after_register_reaches_the_flag() {
    let coord = SeedCoordinator::default();
    let db = std::path::Path::new("/tmp/seed-race-test.db");

    // Cancel with nothing registered: a no-op (nothing to set).
    coord.request_cancel_for_db(db);
    let (_guard, flag) = coord.register_running(db);
    assert!(
        !flag.is_cancelled(),
        "a cancel issued before registration must NOT mark the later flag — \
         this lost-cancel window is exactly what the post-register generation \
         re-check in attempt_seed closes"
    );

    // Cancel after registration reaches the live flag.
    coord.request_cancel_for_db(db);
    assert!(
        flag.is_cancelled(),
        "post-registration cancel reaches the flag"
    );
}
