// GR-1A smoke test fixture: simulated generated gRPC code
// This mimics what protoc-gen-grpc-java would generate
package io.grpc.examples.helloworld;

import io.grpc.stub.StreamObserver;

/**
 * Generated by protoc-gen-grpc-java from helloworld.proto
 */
public final class GreeterGrpc {

    private GreeterGrpc() {}

    public static final String SERVICE_NAME = "helloworld.Greeter";

    /**
     * Base class for Greeter service implementations.
     * Extend this to implement the service.
     */
    public static abstract class GreeterImplBase implements io.grpc.BindableService {

        public void sayHello(HelloRequest request,
                StreamObserver<HelloReply> responseObserver) {
            throw new UnsupportedOperationException("Not implemented");
        }

        @Override
        public io.grpc.ServerServiceDefinition bindService() {
            // Implementation details elided for fixture
            return null;
        }
    }

    // ── Client stub classes ─────────────────────────────────────────────

    /**
     * Creates a new blocking-style stub.
     * GR-2A detection target: calls to this method produce consumer hints.
     */
    public static GreeterBlockingStub newBlockingStub(io.grpc.Channel channel) {
        return new GreeterBlockingStub(channel);
    }

    /**
     * Creates a new ListenableFuture-style stub.
     */
    public static GreeterFutureStub newFutureStub(io.grpc.Channel channel) {
        return new GreeterFutureStub(channel);
    }

    /**
     * Creates a new async stub.
     */
    public static GreeterStub newStub(io.grpc.Channel channel) {
        return new GreeterStub(channel);
    }

    /**
     * Blocking stub for synchronous RPC calls.
     */
    public static final class GreeterBlockingStub {
        private final io.grpc.Channel channel;

        private GreeterBlockingStub(io.grpc.Channel channel) {
            this.channel = channel;
        }

        public HelloReply sayHello(HelloRequest request) {
            // Implementation elided for fixture
            return null;
        }
    }

    /**
     * ListenableFuture stub for async RPC calls.
     */
    public static final class GreeterFutureStub {
        private final io.grpc.Channel channel;

        private GreeterFutureStub(io.grpc.Channel channel) {
            this.channel = channel;
        }
    }

    /**
     * Async stub with StreamObserver callbacks.
     */
    public static final class GreeterStub {
        private final io.grpc.Channel channel;

        private GreeterStub(io.grpc.Channel channel) {
            this.channel = channel;
        }
    }
}
