// GR-1A smoke test fixture: simulated generated gRPC code
// This mimics what protoc-gen-grpc-java would generate
package io.grpc.examples.helloworld;

import io.grpc.stub.StreamObserver;

/**
 * Generated by protoc-gen-grpc-java from helloworld.proto
 */
public final class GreeterGrpc {

    private GreeterGrpc() {}

    public static final String SERVICE_NAME = "helloworld.Greeter";

    /**
     * Base class for Greeter service implementations.
     * Extend this to implement the service.
     */
    public static abstract class GreeterImplBase implements io.grpc.BindableService {

        public void sayHello(HelloRequest request,
                StreamObserver<HelloReply> responseObserver) {
            throw new UnsupportedOperationException("Not implemented");
        }

        @Override
        public io.grpc.ServerServiceDefinition bindService() {
            // Implementation details elided for fixture
            return null;
        }
    }

    // Stub classes elided for fixture
}
