// GR-1A smoke test fixture: simulated generated message class
package io.grpc.examples.helloworld;

/**
 * Generated by protoc from helloworld.proto
 */
public final class HelloRequest {
    private String name;

    public String getName() {
        return name;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static class Builder {
        private String name;

        public Builder setName(String name) {
            this.name = name;
            return this;
        }

        public HelloRequest build() {
            HelloRequest req = new HelloRequest();
            req.name = this.name;
            return req;
        }
    }
}
