// GR-1A smoke test fixture: simulated generated message class
package io.grpc.examples.helloworld;

/**
 * Generated by protoc from helloworld.proto
 */
public final class HelloReply {
    private String message;

    public String getMessage() {
        return message;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static class Builder {
        private String message;

        public Builder setMessage(String message) {
            this.message = message;
            return this;
        }

        public HelloReply build() {
            HelloReply reply = new HelloReply();
            reply.message = this.message;
            return reply;
        }
    }
}
