//! ORIENT-SEGMENT-2 §2.6 (review-3 §4): repo-level orient's Docs surface EXCLUDES
//! rmap's self-generated docs while KEEPING authored docs, RANKED by orientation value
//! (architecture/README first, not alphabetical).
//!
//! This is the agent-level companion to the presentation-side display-cap test
//! (`rgr::presentation::orient_seg2_tests::docs_line_caps_at_headline_limit`). The
//! agent owns the exclusion + ranking; the cap is applied on render.
//!
//! The filter is EVIDENCE-based: it drops entries the doc classifier flagged
//! `generated == true` (the `[generated by rmap map]` first-line marker), never entries
//! matched by bare name — so a user's marker-less doc is never dropped (honesty rule #2:
//! no classification from bare names).

mod common;

use common::FakeAgentStorage;
use repo_graph_agent::{orient, AgentDocEntry, Budget};

fn doc(path: &str, kind: &str, generated: bool) -> AgentDocEntry {
    AgentDocEntry {
        path: path.to_string(),
        kind: kind.to_string(),
        generated,
    }
}

#[test]
fn repo_orient_docs_excludes_generated_keeps_authored_ranked() {
    let mut fake = FakeAgentStorage::new();
    fake.seed_minimal_repo("r1", "my-repo", "snap-1");

    // Authored root docs (kept, ranked: architecture 30 > readme 20) alongside a
    // GENERATED doc whose root-doc NAME (`CONTRIBUTING.md`) would otherwise select it —
    // the `generated` flag is what excludes it, not its name. (Real generated exhaust are
    // the `*_MAP.md` sidecars; giving one a selectable root-doc name is the minimal
    // fixture that proves the filter drops a would-be-relevant generated entry.)
    fake.doc_inventory.insert(
        "r1".to_string(),
        vec![
            doc("README.md", "readme", false),
            doc("ARCHITECTURE.md", "architecture", false),
            doc("CONTRIBUTING.md", "readme", true),
        ],
    );

    let result = orient(&fake, "r1", None, Budget::Small, common::TEST_NOW).unwrap();
    let docs = result
        .documentation
        .expect("authored docs → a documentation section");
    let paths: Vec<&str> = docs
        .relevant_files
        .iter()
        .map(|d| d.path.as_str())
        .collect();

    // Generated entry excluded; no surfaced doc carries the generated flag.
    assert!(
        !paths.contains(&"CONTRIBUTING.md"),
        "generated doc must be excluded: {paths:?}"
    );
    assert!(
        docs.relevant_files.iter().all(|d| !d.generated),
        "no generated doc may reach orient's Docs surface: {paths:?}"
    );

    // Authored docs kept.
    assert!(
        paths.contains(&"README.md"),
        "authored README kept: {paths:?}"
    );
    assert!(
        paths.contains(&"ARCHITECTURE.md"),
        "authored ARCHITECTURE kept: {paths:?}"
    );

    // Ranked by orientation value: the agent orders by relevance priority (architecture
    // kind base 30 > readme kind base 20), so the architecture doc ranks strictly before
    // the README — the ordering the presentation cap relies on to keep the MOST orienting
    // docs when it trims to `DOC_HEADLINE_CAP`.
    let arch_idx = paths.iter().position(|p| *p == "ARCHITECTURE.md").unwrap();
    let readme_idx = paths.iter().position(|p| *p == "README.md").unwrap();
    assert!(
        arch_idx < readme_idx,
        "architecture must rank before README (relevance priority): {paths:?}"
    );
}
