#!/bin/bash
# Build bundled installer from template and platform modules.
#
# Reads scripts/install.template.sh, injects lib/macos.sh and lib/linux.sh
# at the __INJECT_PLATFORM_MODULES__ marker, validates the result, and
# outputs to scripts/dist/install.sh.
#
# Usage:
#   ./scripts/build-installer.sh
#   ./scripts/build-installer.sh --output /path/to/install.sh
#
# The generated installer is a release artifact, not a source file.
# See docs/slices/mac-1-macos-installer.md for deployment details.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/install.template.sh"
OUTPUT_DIR="${SCRIPT_DIR}/dist"
OUTPUT_FILE="${OUTPUT_DIR}/install.sh"
MARKER="# __INJECT_PLATFORM_MODULES__"

# Required functions that must exist after injection
REQUIRED_FUNCTIONS=(
    "setup_macos_daemon_service"
    "install_launchd_plist"
    "start_launchd_service"
    "verify_daemon_health"
    "emit_macos_plist"
)

# ─────────────────────────────────────────────────────────────────────────────
# Argument Parsing
# ─────────────────────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--output <path>]"
            echo ""
            echo "Build bundled installer from template and platform modules."
            echo ""
            echo "Options:"
            echo "  --output <path>  Output path (default: scripts/dist/install.sh)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# ─────────────────────────────────────────────────────────────────────────────
# Validation Helpers
# ─────────────────────────────────────────────────────────────────────────────

die() {
    echo "ERROR: $*" >&2
    exit 1
}

info() {
    echo "[build] $*"
}

# ─────────────────────────────────────────────────────────────────────────────
# Pre-flight Checks
# ─────────────────────────────────────────────────────────────────────────────

[[ -f "${TEMPLATE}" ]] || die "Template not found: ${TEMPLATE}"
[[ -f "${SCRIPT_DIR}/lib/macos.sh" ]] || die "macOS module not found: ${SCRIPT_DIR}/lib/macos.sh"

# Verify marker exists in template
grep -q "${MARKER}" "${TEMPLATE}" || die "Marker not found in template: ${MARKER}"

# ─────────────────────────────────────────────────────────────────────────────
# Generate Bundled Installer
# ─────────────────────────────────────────────────────────────────────────────

info "Building bundled installer..."
info "  Template: ${TEMPLATE}"
info "  Output: ${OUTPUT_FILE}"

# Ensure output directory exists.
output_dir="$(dirname "${OUTPUT_FILE}")"
mkdir -p "${output_dir}" || die "Cannot create output directory: ${output_dir}"

# INSTALL-ROBUSTNESS-2 (assembler honesty, review iteration 5 §5): generate into a
# FRESH temp file in the SAME directory, validate THAT, then atomically move it into
# place. The previous code wrote the group's stdout straight to ${OUTPUT_FILE} with
# `{ ...; } > "${OUTPUT_FILE}"` and then grepped ${OUTPUT_FILE}. If the redirect could
# not open the output for writing (read-only dir/file, sandbox EPERM/EACCES) the write
# produced NOTHING — yet under `set -e` bash does NOT abort on a compound-command
# redirect-open failure (reproduced on bash 3.2: "Permission denied" then "Success!",
# exit 0). So a STALE-but-valid previous ${OUTPUT_FILE} survived, the post-gen checks
# validated the STALE file, and the assembler reported success for an assembly that
# never happened — the repo's cardinal sin of presenting inferred state as observed.
# mktemp in the same dir fails LOUDLY when the dir is unwritable; validating the temp
# means we never validate a stale file; the final mv fails LOUDLY when the destination
# is unwritable — so a write failure now aborts with a named cause and NO false success,
# and a broken/half-written installer never clobbers the last-good ${OUTPUT_FILE}.
tmp_output="$(mktemp "${output_dir}/.install.sh.XXXXXX")" \
    || die "Cannot create a temp output file in ${output_dir} (directory unwritable?)"
trap 'rm -f "${tmp_output}"' EXIT

# Build the installer by processing template line by line
{
    found_marker=false
    in_header=true

    # Emit production header (replaces template header)
    cat << 'PROD_HEADER'
#!/bin/bash
# repo-graph installer
#
# Generated by build-installer.sh - do not edit manually.
# Source: scripts/install.template.sh + lib/*.sh
#
# Usage:
#   curl -fsSL https://github.com/andreirx/repo-graph/releases/latest/download/install.sh | bash
#
# Options (via environment variables):
#   RMAP_VERSION=0.1.0      # Install specific version (default: latest)
#   RMAP_INSTALL_DIR=~/.local/bin  # Install directory
#   RMAP_BINARY_ONLY=1      # Skip daemon service and integrations
#   RMAP_NON_INTERACTIVE=1  # Non-interactive mode (no prompts)
#
# Options (via command line):
#   --version <ver>         # Install specific version
#   --binary-only           # Skip daemon service and integrations
#   --non-interactive       # Non-interactive mode
#   --integrate <hosts>     # Comma-separated hosts to integrate (claude-code,codex)
#   --source               # Build from source (requires Rust toolchain)
#
# See: docs/slices/dist-1-distribution-install-contract.md
#      docs/slices/rel-1-release-pipeline.md

PROD_HEADER

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip template header until we hit 'set -euo pipefail'
        if [[ "${in_header}" == "true" ]]; then
            if [[ "$line" == "set -euo pipefail" ]]; then
                in_header=false
                printf '%s\n' "$line"
            fi
            continue
        fi

        if [[ "$line" == "${MARKER}" ]]; then
            found_marker=true

            # Emit bundled modules header
            cat << 'MODULES_HEADER'

# ═══════════════════════════════════════════════════════════════════════════════
# BUNDLED PLATFORM MODULES
# Generated by build-installer.sh - do not edit manually
# ═══════════════════════════════════════════════════════════════════════════════

MODULES_HEADER

            # Inject macOS module (skip shebang line)
            echo "# --- macOS Platform Module (from lib/macos.sh) ---"
            echo ""
            tail -n +2 "${SCRIPT_DIR}/lib/macos.sh"
            echo ""

            # Inject Linux module if it exists (skip shebang line)
            if [[ -f "${SCRIPT_DIR}/lib/linux.sh" ]]; then
                echo "# --- Linux Platform Module (from lib/linux.sh) ---"
                echo ""
                tail -n +2 "${SCRIPT_DIR}/lib/linux.sh"
                echo ""
            fi

            # Emit bundled modules footer
            cat << 'MODULES_FOOTER'
# ═══════════════════════════════════════════════════════════════════════════════
# END BUNDLED PLATFORM MODULES
# ═══════════════════════════════════════════════════════════════════════════════

MODULES_FOOTER
        else
            printf '%s\n' "$line"
        fi
    done < "${TEMPLATE}"

    if [[ "${found_marker}" != "true" ]]; then
        die "Marker was not processed (should not happen)"
    fi

} > "${tmp_output}" || die "Failed to write the generated installer to ${tmp_output}"

chmod +x "${tmp_output}"

# ─────────────────────────────────────────────────────────────────────────────
# Post-generation Validation
# ─────────────────────────────────────────────────────────────────────────────

info "Validating generated installer..."

# Validation runs against the FRESH temp (never a stale ${OUTPUT_FILE}); only after all
# checks pass is the temp moved into place.

# 1. Verify no unresolved markers remain
if grep -q "__INJECT_" "${tmp_output}"; then
    die "Unresolved injection marker found in output"
fi

# 2. Verify required functions exist
for func in "${REQUIRED_FUNCTIONS[@]}"; do
    if ! grep -q "^${func}()" "${tmp_output}"; then
        die "Required function not found in output: ${func}"
    fi
done

# 3. Shell syntax check
if ! bash -n "${tmp_output}"; then
    die "Shell syntax check failed"
fi

# 4. Verify the bundled modules header is present
if ! grep -q "BUNDLED PLATFORM MODULES" "${tmp_output}"; then
    die "Bundled modules header not found in output"
fi

# All checks passed on the fresh temp — atomically move it into place. A failure here
# (e.g. destination directory read-only) aborts LOUDLY via die rather than leaving the
# stale ${OUTPUT_FILE} while claiming success. Same-directory rename = atomic swap, so a
# reader never sees a half-written installer.
mv -f "${tmp_output}" "${OUTPUT_FILE}" \
    || die "Failed to move the generated installer into place: ${OUTPUT_FILE} (destination unwritable?)"
trap - EXIT

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────

line_count=$(wc -l < "${OUTPUT_FILE}" | tr -d ' ')
info "Success!"
info "  Generated: ${OUTPUT_FILE}"
info "  Lines: ${line_count}"
info "  Functions validated: ${#REQUIRED_FUNCTIONS[@]}"

echo ""
echo "To test locally:"
echo "  bash ${OUTPUT_FILE}"
echo ""
echo "To publish as release asset:"
echo "  gh release upload <tag> ${OUTPUT_FILE}"
