#!/bin/bash
# Build bundled installer from template and platform modules.
#
# Reads scripts/install.template.sh, injects lib/macos.sh and lib/linux.sh
# at the __INJECT_PLATFORM_MODULES__ marker, validates the result, and
# outputs to scripts/dist/install.sh.
#
# Usage:
#   ./scripts/build-installer.sh
#   ./scripts/build-installer.sh --output /path/to/install.sh
#
# The generated installer is a release artifact, not a source file.
# See docs/slices/mac-1-macos-installer.md for deployment details.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/install.template.sh"
OUTPUT_DIR="${SCRIPT_DIR}/dist"
OUTPUT_FILE="${OUTPUT_DIR}/install.sh"
MARKER="# __INJECT_PLATFORM_MODULES__"

# Required functions that must exist after injection
REQUIRED_FUNCTIONS=(
    "setup_macos_daemon_service"
    "install_launchd_plist"
    "start_launchd_service"
    "verify_daemon_health"
    "emit_macos_plist"
)

# ─────────────────────────────────────────────────────────────────────────────
# Argument Parsing
# ─────────────────────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--output <path>]"
            echo ""
            echo "Build bundled installer from template and platform modules."
            echo ""
            echo "Options:"
            echo "  --output <path>  Output path (default: scripts/dist/install.sh)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# ─────────────────────────────────────────────────────────────────────────────
# Validation Helpers
# ─────────────────────────────────────────────────────────────────────────────

die() {
    echo "ERROR: $*" >&2
    exit 1
}

info() {
    echo "[build] $*"
}

# ─────────────────────────────────────────────────────────────────────────────
# Pre-flight Checks
# ─────────────────────────────────────────────────────────────────────────────

[[ -f "${TEMPLATE}" ]] || die "Template not found: ${TEMPLATE}"
[[ -f "${SCRIPT_DIR}/lib/macos.sh" ]] || die "macOS module not found: ${SCRIPT_DIR}/lib/macos.sh"

# Verify marker exists in template
grep -q "${MARKER}" "${TEMPLATE}" || die "Marker not found in template: ${MARKER}"

# ─────────────────────────────────────────────────────────────────────────────
# Generate Bundled Installer
# ─────────────────────────────────────────────────────────────────────────────

info "Building bundled installer..."
info "  Template: ${TEMPLATE}"
info "  Output: ${OUTPUT_FILE}"

# Ensure output directory exists
mkdir -p "$(dirname "${OUTPUT_FILE}")"

# Build the installer by processing template line by line
{
    found_marker=false
    in_header=true

    # Emit production header (replaces template header)
    cat << 'PROD_HEADER'
#!/bin/bash
# repo-graph installer
#
# Generated by build-installer.sh - do not edit manually.
# Source: scripts/install.template.sh + lib/*.sh
#
# Usage:
#   curl -fsSL https://github.com/andreirx/repo-graph/releases/latest/download/install.sh | bash
#
# Options (via environment variables):
#   RMAP_VERSION=0.1.0      # Install specific version (default: latest)
#   RMAP_INSTALL_DIR=~/.local/bin  # Install directory
#   RMAP_BINARY_ONLY=1      # Skip daemon service and integrations
#   RMAP_NON_INTERACTIVE=1  # Non-interactive mode (no prompts)
#
# Options (via command line):
#   --version <ver>         # Install specific version
#   --binary-only           # Skip daemon service and integrations
#   --non-interactive       # Non-interactive mode
#   --integrate <hosts>     # Comma-separated hosts to integrate (claude-code,codex)
#   --source               # Build from source (requires Rust toolchain)
#
# See: docs/slices/dist-1-distribution-install-contract.md
#      docs/slices/rel-1-release-pipeline.md

PROD_HEADER

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip template header until we hit 'set -euo pipefail'
        if [[ "${in_header}" == "true" ]]; then
            if [[ "$line" == "set -euo pipefail" ]]; then
                in_header=false
                printf '%s\n' "$line"
            fi
            continue
        fi

        if [[ "$line" == "${MARKER}" ]]; then
            found_marker=true

            # Emit bundled modules header
            cat << 'MODULES_HEADER'

# ═══════════════════════════════════════════════════════════════════════════════
# BUNDLED PLATFORM MODULES
# Generated by build-installer.sh - do not edit manually
# ═══════════════════════════════════════════════════════════════════════════════

MODULES_HEADER

            # Inject macOS module (skip shebang line)
            echo "# --- macOS Platform Module (from lib/macos.sh) ---"
            echo ""
            tail -n +2 "${SCRIPT_DIR}/lib/macos.sh"
            echo ""

            # Inject Linux module if it exists (skip shebang line)
            if [[ -f "${SCRIPT_DIR}/lib/linux.sh" ]]; then
                echo "# --- Linux Platform Module (from lib/linux.sh) ---"
                echo ""
                tail -n +2 "${SCRIPT_DIR}/lib/linux.sh"
                echo ""
            fi

            # Emit bundled modules footer
            cat << 'MODULES_FOOTER'
# ═══════════════════════════════════════════════════════════════════════════════
# END BUNDLED PLATFORM MODULES
# ═══════════════════════════════════════════════════════════════════════════════

MODULES_FOOTER
        else
            printf '%s\n' "$line"
        fi
    done < "${TEMPLATE}"

    if [[ "${found_marker}" != "true" ]]; then
        die "Marker was not processed (should not happen)"
    fi

} > "${OUTPUT_FILE}"

chmod +x "${OUTPUT_FILE}"

# ─────────────────────────────────────────────────────────────────────────────
# Post-generation Validation
# ─────────────────────────────────────────────────────────────────────────────

info "Validating generated installer..."

# 1. Verify no unresolved markers remain
if grep -q "__INJECT_" "${OUTPUT_FILE}"; then
    die "Unresolved injection marker found in output"
fi

# 2. Verify required functions exist
for func in "${REQUIRED_FUNCTIONS[@]}"; do
    if ! grep -q "^${func}()" "${OUTPUT_FILE}"; then
        die "Required function not found in output: ${func}"
    fi
done

# 3. Shell syntax check
if ! bash -n "${OUTPUT_FILE}"; then
    die "Shell syntax check failed"
fi

# 4. Verify the bundled modules header is present
if ! grep -q "BUNDLED PLATFORM MODULES" "${OUTPUT_FILE}"; then
    die "Bundled modules header not found in output"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────

line_count=$(wc -l < "${OUTPUT_FILE}" | tr -d ' ')
info "Success!"
info "  Generated: ${OUTPUT_FILE}"
info "  Lines: ${line_count}"
info "  Functions validated: ${#REQUIRED_FUNCTIONS[@]}"

echo ""
echo "To test locally:"
echo "  bash ${OUTPUT_FILE}"
echo ""
echo "To publish as release asset:"
echo "  gh release upload <tag> ${OUTPUT_FILE}"
