#!/bin/bash
# repo-graph installer template
#
# THIS IS A SOURCE TEMPLATE. Do not run directly via curl|bash.
# The production installer is generated by build-installer.sh and published
# as a release asset.
#
# Production usage:
#   curl -fsSL https://github.com/andreirx/repo-graph/releases/latest/download/install.sh | bash
#
# Development usage (from checkout):
#   ./scripts/install.template.sh
#
# Options (via environment variables):
#   RMAP_VERSION=0.1.0      # Install specific version (default: latest)
#   RMAP_INSTALL_DIR=~/.local/bin  # Install directory
#   RMAP_BINARY_ONLY=1      # Skip daemon service and integrations
#   RMAP_NON_INTERACTIVE=1  # Non-interactive mode (no prompts)
#
# Options (via command line):
#   --version <ver>         # Install specific version
#   --binary-only           # Skip daemon service and integrations
#   --non-interactive       # Non-interactive mode
#   --integrate <hosts>     # Comma-separated hosts to integrate (claude-code,codex)
#   --source               # Build from source (requires Rust toolchain)
#
# See: docs/slices/dist-1-distribution-install-contract.md
#      docs/slices/rel-1-release-pipeline.md

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Script Location Detection
# ─────────────────────────────────────────────────────────────────────────────

# Detect script directory. Empty if running via curl|bash (bundled mode).
if [[ -n "${BASH_SOURCE[0]:-}" ]] && [[ -f "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    SCRIPT_DIR=""
fi

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

# GitHub repository
REPO_OWNER="${RMAP_REPO_OWNER:-andreirx}"
REPO_NAME="repo-graph"
RELEASES_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases"
# INSTALL-ROBUSTNESS-2 (A): resolve "latest" from this github.com redirect FIRST
# (same host as the binary download below — effectively not rate-limited), before
# ever touching the 60/hr/IP api.github.com endpoint.
LATEST_RELEASE_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/latest"
DOWNLOAD_BASE="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download"

# Default install directory (user-local, no sudo required)
DEFAULT_INSTALL_DIR="${HOME}/.local/bin"

# Platform-specific paths and constants
# These are fallbacks for bundled mode (curl|bash). In modular mode,
# lib/macos.sh or lib/linux.sh may override these.
if [[ "$(uname -s)" == "Darwin" ]]; then
    CONFIG_DIR="${HOME}/Library/Application Support/repo-graph"
    DATA_DIR="${HOME}/Library/Application Support/repo-graph"
    LOG_DIR="${HOME}/Library/Logs/repo-graph"
    # launchd constants (must match lib/macos.sh)
    MACOS_LAUNCHAGENTS_DIR="${HOME}/Library/LaunchAgents"
    MACOS_SERVICE_LABEL="com.repo-graph.rmapd"
    MACOS_PLIST_NAME="${MACOS_SERVICE_LABEL}.plist"
else
    CONFIG_DIR="${HOME}/.config/rmap"
    DATA_DIR="${HOME}/.local/share/rmap"
    LOG_DIR="${HOME}/.local/share/rmap/logs"
    # systemd constants
    LINUX_SERVICE_MODE="${LINUX_SERVICE_MODE:-manual}"
fi

# State
VERSION=""
INSTALL_DIR=""
BINARY_ONLY="${RMAP_BINARY_ONLY:-false}"
NON_INTERACTIVE="${RMAP_NON_INTERACTIVE:-false}"
BUILD_FROM_SOURCE=false
INTEGRATE_HOSTS=""
# Resolved by resolve_version (A) / set by the platform daemon setup (B) so the
# final summary can state which daemon-start case occurred.
RESOLVED_TAG=""
DAEMON_OUTCOME=""

# ─────────────────────────────────────────────────────────────────────────────
# Utilities
# ─────────────────────────────────────────────────────────────────────────────

info() {
    echo "[info] $*"
}

warn() {
    echo "[warn] $*" >&2
}

error() {
    echo "[error] $*" >&2
    exit 1
}

confirm() {
    local prompt="$1"
    local default="${2:-n}"

    if [[ "${NON_INTERACTIVE}" == "true" ]]; then
        return 0
    fi

    if [[ "${default}" == "y" ]]; then
        read -r -p "${prompt} [Y/n]: " response
        [[ -z "${response}" || "${response}" =~ ^[Yy] ]]
    else
        read -r -p "${prompt} [y/N]: " response
        [[ "${response}" =~ ^[Yy] ]]
    fi
}

command_exists() {
    command -v "$1" &> /dev/null
}

# __INJECT_PLATFORM_MODULES__

# ─────────────────────────────────────────────────────────────────────────────
# Platform Detection
# ─────────────────────────────────────────────────────────────────────────────

detect_platform() {
    local os arch

    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    arch="$(uname -m)"

    # Normalize architecture
    case "${arch}" in
        x86_64|amd64)
            arch="x86_64"
            ;;
        arm64|aarch64)
            arch="aarch64"
            ;;
        *)
            error "Unsupported architecture: ${arch}"
            ;;
    esac

    # Normalize platform
    case "${os}" in
        darwin)
            PLATFORM="darwin"
            ;;
        linux)
            PLATFORM="linux"
            ;;
        *)
            error "Unsupported platform: ${os}"
            ;;
    esac

    ARCH="${arch}"
    info "Detected platform: ${PLATFORM}-${ARCH}"
}

# Source platform-specific module after platform detection.
# Called from main() after detect_platform().
#
# In modular mode (run from checkout): sources lib/macos.sh or lib/linux.sh
# In bundled mode (generated installer): libs are already inlined
source_platform_module() {
    # Check if platform functions are already defined (bundled installer).
    # This check must come FIRST because the bundled installer may be run
    # from a file path (bash install.sh), not just piped (curl|bash).
    if declare -f setup_macos_daemon_service > /dev/null 2>&1 || \
       declare -f setup_linux_daemon_service > /dev/null 2>&1; then
        PLATFORM_MODULE_LOADED=true
        return
    fi

    # Modular mode: try to source platform modules from lib/
    if [[ -z "${SCRIPT_DIR}" ]]; then
        # No SCRIPT_DIR and no bundled functions - truly headless mode
        PLATFORM_MODULE_LOADED=false
        return
    fi

    local lib_dir="${SCRIPT_DIR}/lib"

    case "${PLATFORM}" in
        darwin)
            if [[ -f "${lib_dir}/macos.sh" ]]; then
                source "${lib_dir}/macos.sh"
                PLATFORM_MODULE_LOADED=true
            else
                PLATFORM_MODULE_LOADED=false
            fi
            ;;
        linux)
            if [[ -f "${lib_dir}/linux.sh" ]]; then
                source "${lib_dir}/linux.sh"
                PLATFORM_MODULE_LOADED=true
            else
                PLATFORM_MODULE_LOADED=false
            fi
            ;;
        *)
            PLATFORM_MODULE_LOADED=false
            ;;
    esac
}

# ─────────────────────────────────────────────────────────────────────────────
# Toolchain Detection (informational only, not required for binary install)
# ─────────────────────────────────────────────────────────────────────────────

detect_toolchains() {
    info "Detecting toolchains..."

    # Rust (required for source build)
    if command_exists rustc; then
        local rust_version
        rust_version="$(rustc --version 2>/dev/null | awk '{print $2}')"
        info "  Rust: ${rust_version}"
        RUST_AVAILABLE=true
    else
        info "  Rust: not found"
        RUST_AVAILABLE=false
    fi

    # Cargo
    if command_exists cargo; then
        local cargo_version
        cargo_version="$(cargo --version 2>/dev/null | awk '{print $2}')"
        info "  Cargo: ${cargo_version}"
    fi

    # Node.js (not required for rmap, informational only)
    if command_exists node; then
        local node_version
        node_version="$(node --version 2>/dev/null)"
        info "  Node.js: ${node_version}"
    else
        info "  Node.js: not found (not required)"
    fi

    # npm (not required for rmap, informational only)
    if command_exists npm; then
        local npm_version
        npm_version="$(npm --version 2>/dev/null)"
        info "  npm: ${npm_version}"
    else
        info "  npm: not found (not required)"
    fi

    # Note about requirements
    if [[ "${BUILD_FROM_SOURCE}" == "true" && "${RUST_AVAILABLE}" != "true" ]]; then
        error "Source build requested but Rust toolchain not found. Install from: https://rustup.rs"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Version Resolution
# ─────────────────────────────────────────────────────────────────────────────

# Resolve VERSION to a concrete release tag when it is empty or "latest".
#
# INSTALL-ROBUSTNESS-2 (A): the OLD path resolved "latest" via a SINGLE
# api.github.com call. Unauthenticated GitHub API calls are capped at 60/hr/IP;
# on a shared IP the install died with 403 for the sake of ONE string — while the
# actual binary host (github.com, used by download_binary) worked fine. The fix
# resolves the tag from github.com FIRST (same host as the download, effectively
# not rate-limited), and only falls back to the API (now GITHUB_TOKEN-aware).
#
# Orchestration only: the two network mechanisms live in resolve_version_via_redirect
# (primary) and resolve_version_via_api (fallback) — split so a bash test harness can
# stub each independently (see scripts/test-install-robustness-2.sh). Each sets the
# RESOLVED_TAG global and NEVER aborts, so the fallback decision stays here.
resolve_version() {
    if [[ -n "${VERSION}" && "${VERSION}" != "latest" ]]; then
        info "Using specified version: ${VERSION}"
        return
    fi

    info "Fetching latest version..."

    if ! command_exists curl; then
        error "curl is required but not found"
    fi

    # Primary: github.com redirect (no API, effectively not rate-limited).
    RESOLVED_TAG=""
    resolve_version_via_redirect

    # Fallback: the api.github.com call (rate-limited; GITHUB_TOKEN-authenticated
    # when the token is set), only if the redirect did not yield a tag.
    if [[ -z "${RESOLVED_TAG}" ]]; then
        warn "Could not resolve the version from the github.com redirect; falling back to the GitHub API."
        resolve_version_via_api
    fi

    if [[ -z "${RESOLVED_TAG}" ]]; then
        error "Could not determine the latest version from github.com (redirect) or api.github.com (API) — likely a network/proxy issue or the GitHub API rate limit (60/hr/IP unauthenticated). Retry, set GITHUB_TOKEN to raise the API limit, or pin the version to skip the lookup entirely: RMAP_VERSION=<ver> curl -fsSL <install-url> | bash"
    fi

    # Remove 'v' prefix (tags are published as vX.Y.Z).
    VERSION="${RESOLVED_TAG#v}"
    info "Latest version: ${VERSION}"
}

# PRIMARY resolver: parse the latest tag from the redirect Location of
# github.com/<owner>/<repo>/releases/latest via a HEAD request — the SAME host as
# the binary download, so it is not subject to the api.github.com rate limit.
# Sets RESOLVED_TAG on success; leaves it empty on any failure so resolve_version
# can fall back. Returns 0 unconditionally (failure is signalled via empty
# RESOLVED_TAG, never a nonzero exit — resolve_version owns the fallback decision).
#
# Observability discipline (preserved from the api-only version — its comment
# history records WHY): the curl is split OUT of the parse so its exit code is
# observable (a "curl | sed" pipeline assigned via `local` masks curl's status);
# the URL is logged before the request; -S surfaces curl's own error line; and the
# --connect-timeout/--max-time bounds are NOT weakened (a stall fails in seconds).
resolve_version_via_redirect() {
    RESOLVED_TAG=""
    info "  HEAD ${LATEST_RELEASE_URL}"

    # -I  = HEAD (do not download the release page body).
    # -o /dev/null + -w '%{redirect_url}' = emit ONLY the 302 Location target,
    #   e.g. https://github.com/<owner>/<repo>/releases/tag/vX.Y.Z. No -L: we do
    #   NOT follow the redirect — we only want the tag out of the redirect target.
    local redirect_url curl_exit
    redirect_url="$(curl -fsSI -o /dev/null -w '%{redirect_url}' \
        --connect-timeout 10 --max-time 30 "${LATEST_RELEASE_URL}")" && curl_exit=0 || curl_exit=$?

    if [[ "${curl_exit}" -ne 0 ]]; then
        warn "  github.com redirect probe failed (curl exit ${curl_exit})"
        return 0
    fi

    # Parse the tag out of .../releases/tag/<tag>. If the redirect shape is not the
    # expected /releases/tag/<tag> (e.g. GitHub changed it), leave RESOLVED_TAG
    # empty so the API fallback runs — do NOT ship a guessed tag.
    if [[ "${redirect_url}" == *"/releases/tag/"* ]]; then
        local tag="${redirect_url##*/releases/tag/}"
        tag="${tag%%[/?#]*}"     # strip any trailing path / query / fragment
        RESOLVED_TAG="${tag}"
    else
        warn "  Unexpected redirect target (no /releases/tag/): ${redirect_url:-<empty>}"
    fi
    return 0
}

# FALLBACK resolver: the original api.github.com/releases/latest call, now sending
# Authorization: Bearer $GITHUB_TOKEN when GITHUB_TOKEN is set (raises the 60/hr/IP
# unauthenticated cap). Sets RESOLVED_TAG on success; leaves it empty on failure.
# Same split-curl observable-exit-code discipline as the redirect path. Returns 0
# unconditionally (see resolve_version_via_redirect).
resolve_version_via_api() {
    RESOLVED_TAG=""
    info "  GET ${RELEASES_URL}/latest"

    local -a curl_args=(-fsSL --connect-timeout 10 --max-time 30)
    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        curl_args+=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
        info "  (authenticating with GITHUB_TOKEN)"
    fi

    local api_response curl_exit
    api_response="$(curl "${curl_args[@]}" "${RELEASES_URL}/latest")" && curl_exit=0 || curl_exit=$?

    if [[ "${curl_exit}" -ne 0 ]]; then
        warn "  api.github.com request failed (curl exit ${curl_exit}) — network/proxy issue or the API rate limit (set GITHUB_TOKEN to raise it)."
        return 0
    fi

    # Parse tag_name from the API JSON (parse logic unchanged from the original).
    # The trailing `|| true` guards against `pipefail`: grep exits 1 when the
    # response has no tag_name, which would otherwise abort under `set -o pipefail`
    # instead of leaving RESOLVED_TAG empty for an honest error.
    local tag
    tag="$(printf '%s' "${api_response}" | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/' || true)"
    RESOLVED_TAG="${tag}"
    return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# Download and Verify
# ─────────────────────────────────────────────────────────────────────────────

download_binary() {
    local artifact="rmap-${VERSION}-${PLATFORM}-${ARCH}.tar.gz"
    local download_url="${DOWNLOAD_BASE}/v${VERSION}/${artifact}"
    local checksum_url="${download_url}.sha256"

    local tmp_dir
    tmp_dir="$(mktemp -d)"
    trap "rm -rf '${tmp_dir}'" EXIT

    # Network step: download the release tarball + checksum from github.com
    # (NOT api.github.com — that host is only used by resolve_version). Log the
    # exact URL before each request and capture each curl exit code so a failure
    # names the URL + exit code instead of failing silently.
    #
    # Timeouts: --connect-timeout 10 fails fast if the connection cannot be
    # established (the stall failure mode). The tarball is a multi-MB binary, so
    # it gets a generous --max-time 600 (10 min) backstop — large enough not to
    # abort a legitimately slow-but-progressing download, small enough that a
    # wedged transfer cannot hang forever. The checksum is a few bytes, so it
    # reuses the tight --max-time 30 (same as the API call).
    # (A future refinement could swap the tarball's fixed --max-time for
    # --speed-limit/--speed-time to abort only on a true mid-transfer stall; that
    # is out of scope for this logging/timeout slice.)
    info "Downloading ${artifact}..."
    info "  GET ${download_url}"
    local dl_exit
    curl -fsSL --connect-timeout 10 --max-time 600 -o "${tmp_dir}/${artifact}" "${download_url}" && dl_exit=0 || dl_exit=$?
    if [[ "${dl_exit}" -ne 0 ]]; then
        error "Failed to download ${artifact} (curl exit ${dl_exit}) from ${download_url}"
    fi

    info "Downloading checksum..."
    info "  GET ${checksum_url}"
    local sum_exit
    curl -fsSL --connect-timeout 10 --max-time 30 -o "${tmp_dir}/${artifact}.sha256" "${checksum_url}" && sum_exit=0 || sum_exit=$?
    if [[ "${sum_exit}" -ne 0 ]]; then
        error "Failed to download checksum (curl exit ${sum_exit}) from ${checksum_url}"
    fi

    info "Verifying checksum..."
    cd "${tmp_dir}"
    if command_exists shasum; then
        if ! shasum -a 256 -c "${artifact}.sha256"; then
            error "Checksum verification failed!"
        fi
    elif command_exists sha256sum; then
        if ! sha256sum -c "${artifact}.sha256"; then
            error "Checksum verification failed!"
        fi
    else
        warn "No checksum tool found (shasum or sha256sum). Skipping verification."
    fi

    info "Extracting archive..."
    tar -xzf "${artifact}"

    # Move binaries to install location
    EXTRACTED_DIR="rmap-${VERSION}-${PLATFORM}-${ARCH}"
    if [[ ! -f "${EXTRACTED_DIR}/rmap" ]]; then
        error "CLI binary (rmap) not found in archive"
    fi
    if [[ ! -f "${EXTRACTED_DIR}/rmapd" ]]; then
        error "Daemon binary (rmapd) not found in archive"
    fi
    if [[ ! -f "${EXTRACTED_DIR}/rgistr" ]]; then
        error "rgistr binary not found in archive"
    fi

    # Create install directory if needed
    mkdir -p "${INSTALL_DIR}"

    info "Installing CLI to ${INSTALL_DIR}/rmap..."
    install -m 755 "${EXTRACTED_DIR}/rmap" "${INSTALL_DIR}/rmap"

    info "Installing daemon to ${INSTALL_DIR}/rmapd..."
    install -m 755 "${EXTRACTED_DIR}/rmapd" "${INSTALL_DIR}/rmapd"

    info "Installing rgistr to ${INSTALL_DIR}/rgistr..."
    install -m 755 "${EXTRACTED_DIR}/rgistr" "${INSTALL_DIR}/rgistr"

    # Verify installation
    if ! "${INSTALL_DIR}/rmap" --version > /dev/null 2>&1; then
        # On macOS, Gatekeeper may block unsigned binaries
        if [[ "${PLATFORM}" == "darwin" ]]; then
            warn ""
            warn "macOS Gatekeeper may have blocked the binaries."
            warn "To allow, run:"
            warn "  xattr -d com.apple.quarantine ${INSTALL_DIR}/rmap"
            warn "  xattr -d com.apple.quarantine ${INSTALL_DIR}/rmapd"
            warn "  xattr -d com.apple.quarantine ${INSTALL_DIR}/rgistr"
            warn ""
            warn "Or: System Preferences -> Security & Privacy -> Allow"
            warn ""

            if confirm "Run xattr commands now?"; then
                xattr -d com.apple.quarantine "${INSTALL_DIR}/rmap" 2>/dev/null || true
                xattr -d com.apple.quarantine "${INSTALL_DIR}/rmapd" 2>/dev/null || true
                xattr -d com.apple.quarantine "${INSTALL_DIR}/rgistr" 2>/dev/null || true

                if "${INSTALL_DIR}/rmap" --version > /dev/null 2>&1; then
                    info "Binaries unblocked successfully"
                else
                    error "Binary verification still failed after unblocking"
                fi
            fi
        else
            error "Binary verification failed"
        fi
    fi

    local installed_version
    installed_version="$("${INSTALL_DIR}/rmap" --version 2>/dev/null | head -1)"
    info "Installed: ${installed_version}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Source Build
# ─────────────────────────────────────────────────────────────────────────────

build_from_source() {
    info "Building from source..."

    if [[ "${RUST_AVAILABLE}" != "true" ]]; then
        error "Rust toolchain required for source build. Install from: https://rustup.rs"
    fi

    local tmp_dir
    tmp_dir="$(mktemp -d)"
    trap "rm -rf '${tmp_dir}'" EXIT

    info "Cloning repository..."
    if ! command_exists git; then
        error "git is required for source build"
    fi

    git clone --depth 1 --branch "v${VERSION}" \
        "https://github.com/${REPO_OWNER}/${REPO_NAME}.git" \
        "${tmp_dir}/repo-graph"

    cd "${tmp_dir}/repo-graph/rust"

    info "Building release binaries..."
    cargo build --release -p repo-graph-rgr -p rmapd

    # Install Rust binaries
    mkdir -p "${INSTALL_DIR}"
    install -m 755 "target/release/rmap" "${INSTALL_DIR}/rmap"
    install -m 755 "target/release/rmapd" "${INSTALL_DIR}/rmapd"

    # Build rgistr (required - rgistr is a first-class release component)
    if ! command_exists node || ! command_exists npm; then
        error "Node.js and npm required for source build (rgistr is a first-class component)"
    fi

    info "Building rgistr..."
    cd "${tmp_dir}/repo-graph/tools/rgistr"
    npm ci
    npm run bundle
    ./scripts/build-sea.sh "${PLATFORM}" "${ARCH}"
    install -m 755 "build/rgistr-${PLATFORM}-${ARCH}" "${INSTALL_DIR}/rgistr"

    local installed_version
    installed_version="$("${INSTALL_DIR}/rmap" --version 2>/dev/null | head -1)"
    info "Installed: ${installed_version}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Directory Setup
# ─────────────────────────────────────────────────────────────────────────────

create_directories() {
    info "Creating directories..."

    mkdir -p "${CONFIG_DIR}"
    mkdir -p "${DATA_DIR}/databases"
    mkdir -p "${DATA_DIR}/sessions"
    mkdir -p "${LOG_DIR}"

    # Set permissions
    chmod 700 "${CONFIG_DIR}"
    chmod 700 "${DATA_DIR}"
    chmod 700 "${LOG_DIR}"

    info "  Config: ${CONFIG_DIR}"
    info "  Data: ${DATA_DIR}"
    info "  Logs: ${LOG_DIR}"
}

# ─────────────────────────────────────────────────────────────────────────────
# PATH Setup
# ─────────────────────────────────────────────────────────────────────────────

setup_path() {
    # Check if install dir is in PATH
    if [[ ":${PATH}:" == *":${INSTALL_DIR}:"* ]]; then
        info "${INSTALL_DIR} is already in PATH"
        return
    fi

    info "${INSTALL_DIR} is not in PATH"

    if [[ "${NON_INTERACTIVE}" == "true" ]]; then
        warn "Add to PATH manually: export PATH=\"${INSTALL_DIR}:\$PATH\""
        return
    fi

    # Detect shell profile
    local shell_profile=""
    local shell_name=""

    case "${SHELL}" in
        */zsh)
            shell_name="zsh"
            shell_profile="${HOME}/.zshrc"
            ;;
        */bash)
            shell_name="bash"
            if [[ -f "${HOME}/.bash_profile" ]]; then
                shell_profile="${HOME}/.bash_profile"
            else
                shell_profile="${HOME}/.bashrc"
            fi
            ;;
        *)
            shell_profile="${HOME}/.profile"
            ;;
    esac

    if confirm "Add ${INSTALL_DIR} to PATH in ${shell_profile}?"; then
        local path_line="export PATH=\"${INSTALL_DIR}:\$PATH\""

        # Check if already added
        if grep -q "${INSTALL_DIR}" "${shell_profile}" 2>/dev/null; then
            info "PATH entry already exists in ${shell_profile}"
        else
            echo "" >> "${shell_profile}"
            echo "# repo-graph" >> "${shell_profile}"
            echo "${path_line}" >> "${shell_profile}"
            info "Added to ${shell_profile}"
            info ""
            info "Run 'source ${shell_profile}' or start a new terminal to update PATH"
        fi
    else
        warn "Add to PATH manually: export PATH=\"${INSTALL_DIR}:\$PATH\""
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Daemon Socket Liveness (INSTALL-ROBUSTNESS-2 B) — shared, platform-agnostic
# ─────────────────────────────────────────────────────────────────────────────
#
# These live in the TEMPLATE (injected ONCE) on purpose. The old daemon-start
# retry loop was duplicated in BOTH lib/macos.sh and lib/linux.sh; the bundled
# installer injects both, so the Linux copy shadowed the macOS one and a macOS
# install ran Linux health logic (stat of a ~/.local/share/rmap/daemon.pid file
# that never exists on macOS) → the daemon was reported "failed" while launchd
# had it running. The predicate is not platform-specific — it is "does the daemon
# answer on its Unix socket?" — so it is defined once, here.

# Source of truth for "is the daemon usable": does it ANSWER a ping ON ITS UNIX SOCKET?
# This MUST be a PURE socket-liveness predicate — success iff the daemon answers on the
# socket — INDEPENDENT of (a) the binary/dir/launchd-service/plist checks AND (b) the
# ambient RMAP_TRANSPORT.
#
# It reads ONLY the `socket_ping` probe out of `rmap doctor --json`. NOT the doctor exit
# code: `rmap doctor` is an AGGREGATE health verdict — it exits nonzero unless ALL probes
# pass (binaries present, dirs present, launchd/plist healthy, socket answering, storage,
# …; see rgr::commands::doctor::execute_doctor, healthy = 0 fails). A daemon can ANSWER on
# the socket while doctor still exits nonzero (e.g. the plist or a binary-dir probe fails
# on a partial/relocated install) — using doctor's exit code would misreport a RUNNING
# daemon as failed, the exact honesty bug this slice removes.
#
# WHY the `RMAP_TRANSPORT=socket` prefix is load-bearing: the `socket_ping` probe issues
# its ping() through the CLI's DaemonClient, whose transport is chosen by RMAP_TRANSPORT
# (rgr daemon_client::transport — verified: `stdio` ⇒ SPAWN an `rmapd` subprocess and talk
# over stdio; `socket` ⇒ the Unix socket with NO fallback; unset ⇒ socket-then-stdio only
# on EPERM/EACCES). So if RMAP_TRANSPORT=stdio is present in the environment, `socket_ping`
# can pass by pinging a freshly-SPAWNED subprocess while the real socket daemon is wedged —
# i.e. "success without an answering socket", which this slice's stop condition forbids.
# This is NOT hypothetical: scripts/dogfood-isolated.sh EXPORTS RMAP_TRANSPORT=stdio as its
# isolation lever, so a probe that trusted the ambient value would be fooled in that very
# environment. Forcing RMAP_TRANSPORT=socket for THIS one invocation makes `socket_ping`
# pass IFF the socket daemon itself answered a ping. (The socket_connect probe that gates
# socket_ping — a real connect() to the RESOLVED path — has already proven the socket is
# bound; forcing socket transport makes the ping travel that same socket instead of a
# subprocess.) The prefix is command-scoped, so it never leaks into the installer env.
#
# The probe resolves the socket via RMAP_SOCKET_PATH → canonical → legacy, so it honors
# RMAP_SOCKET_PATH (the isolated-daemon tests and a field install both probe the right
# socket). `rmap doctor --json` ALWAYS prints the full per-probe JSON regardless of the
# aggregate verdict, then sets its exit code — so we ignore the exit code and read the
# socket_ping verdict from the body. No jq dependency: the JSON is serde pretty-printed
# with `name` immediately before `passed` in each probe object (ProbeOutput field order),
# so the first `"passed":` line after `"name": "socket_ping"` is socket_ping's own — a
# two-line awk match, robust to whitespace. `|| true` keeps a nonzero doctor exit (expected
# on any unhealthy aggregate) from tripping `set -e` under `pipefail`; the verdict is the
# captured socket_ping value, not the pipeline status.
daemon_socket_answers() {
    local ping_passed
    ping_passed="$(RMAP_TRANSPORT=socket "${INSTALL_DIR}/rmap" doctor --json 2>/dev/null | awk '
        /"name": "socket_ping"/ { in_ping = 1; next }
        in_ping && /"passed":/  { print ($0 ~ /true/) ? "true" : "false"; exit }
    ')" || true
    [[ "${ping_passed}" == "true" ]]
}

# Best-effort daemon PID for the REPORT ONLY (never the liveness predicate). Uses
# pgrep (present on macOS and Linux) rather than the platform get_daemon_pid()
# helpers, which collide by name across the two bundled platform modules.
daemon_pid_best_effort() {
    # `|| true`: under `set -o pipefail`, pgrep exits nonzero when no rmapd matches
    # (e.g. a TOCTOU race after the socket answered), which would otherwise abort at
    # the `pid="$(...)"` call site. The PID is report-only, so absence is fine.
    pgrep -x rmapd 2>/dev/null | head -1 || true
}

# Report-only: the ACTUAL daemon socket path `rmap` resolved and probed, for the honest
# daemon-start FAILURE message. It parses rgr's OWN `socket_path` probe out of the SAME
# `rmap doctor --json` the liveness predicate reads — so the message names the path that
# was REALLY probed, not a value reconstructed in bash.
#
# WHY parse instead of reconstructing as ${RMAP_SOCKET_PATH:-<canonical>}: rgr's resolver
# (platform-paths::resolve_socket_path — verified) can pick the LEGACY $HOME socket over
# the canonical one in the migration case — canonical UNreachable but legacy reachable,
# where "reachable" is a BARE connect() with no ping. So a legacy socket that connects but
# whose ping fails is exactly the FAILURE path here, and its chosen path is the legacy one
# while the canonical default differs — a bash ${RMAP_SOCKET_PATH:-<canonical>} would name
# the WRONG socket. Reading rgr's chosen path keeps the message truthful in that case and
# under an RMAP_SOCKET_PATH override alike.
#
# Forces RMAP_TRANSPORT=socket for parity with daemon_socket_answers (path resolution is
# transport-independent, but keeping the two calls identical avoids surprises). The
# `socket_path` probe message is "<path> (exists)" | "<path> (not found)"; the awk strips
# the JSON key, the quotes, and the trailing status. $1 is the canonical default, used ONLY
# if the JSON yields no absolute path (a stable default beats an empty line). NEVER the
# liveness predicate — reporting only.
resolved_socket_path() {
    local default_path="$1"
    local parsed
    parsed="$(RMAP_TRANSPORT=socket "${INSTALL_DIR}/rmap" doctor --json 2>/dev/null | awk '
        /"name": "socket_path"/ { in_sp = 1; next }
        in_sp && /"message":/ {
            line = $0
            sub(/^[[:space:]]*"message":[[:space:]]*"/, "", line)   # strip key + opening quote
            sub(/".*$/, "", line)                                    # strip closing quote + trailing
            sub(/ \(exists\)$/, "", line)                            # strip the resolution-status suffix
            sub(/ \(not found\)$/, "", line)
            print line
            exit
        }
    ')" || true
    # Accept only an absolute path (guards the degenerate "could not determine" message and
    # any parse miss); otherwise fall back to the caller's canonical default.
    if [[ "${parsed}" == /* ]]; then
        printf '%s' "${parsed}"
    else
        printf '%s' "${default_path}"
    fi
}

# Wait up to max_attempts × delay for the daemon socket to answer. The predicate is
# socket liveness (daemon_socket_answers), NOT the launcher's exit status: a
# late-arriving daemon (launchd/systemd throttling, slow first spawn) flips this to
# success within the budget. Returns 0 as soon as the socket answers, else 1.
#
# INSTALL-ROBUSTNESS-2 (B), review-7 fix — the FINAL-WINDOW RACE: this loop must END on a
# probe, never on a sleep. It probes once up front, then performs max_attempts waits, each
# followed by a RE-PROBE — INCLUDING a probe AFTER the last wait. So a daemon that comes up
# during the final wait window is caught (→ "started"), and failure is returned ONLY
# immediately after a probe that just observed the socket NOT answering. The old loop slept
# AFTER its last probe and then returned failure with no probe following that sleep, so a
# daemon that arrived during the final ~delay seconds was misreported "failed" while the
# socket was in fact answering — the exact violation of this slice's stop condition
# "never report failure while the socket answers" (and contract B.3/B.4). The wait budget is
# unchanged (max_attempts waits × delay ≈ the old ~10s); the fix adds one probe at the end
# and removes the trailing dead sleep.
verify_daemon_health() {
    local max_attempts="${1:-5}"
    local delay="${2:-2}"
    local attempt=0

    info "Verifying daemon health (probing the socket)..."

    # Probe up front — catches a socket that answers immediately (e.g. the daemon came up
    # between the launcher call and now) with no wait.
    if daemon_socket_answers; then
        return 0
    fi
    # Then wait-and-re-probe up to max_attempts times. The re-probe runs AFTER each sleep,
    # including the last one, so the loop's final action before `return 1` is always a fresh
    # probe — never a sleep whose window a late-arriving daemon could slip through unseen.
    while [[ ${attempt} -lt ${max_attempts} ]]; do
        attempt=$((attempt + 1))
        info "  Attempt ${attempt}/${max_attempts}: daemon socket not answering yet, waiting ${delay}s..."
        sleep "${delay}"
        if daemon_socket_answers; then
            return 0
        fi
    done

    return 1
}

# ─────────────────────────────────────────────────────────────────────────────
# Daemon Service
# ─────────────────────────────────────────────────────────────────────────────

setup_daemon_service() {
    if [[ "${BINARY_ONLY}" == "true" ]]; then
        info "Skipping daemon service (--binary-only)"
        return
    fi

    info ""

    # Dispatch to platform-specific module
    case "${PLATFORM}" in
        darwin)
            if [[ "${PLATFORM_MODULE_LOADED}" == "true" ]] && declare -f setup_macos_daemon_service > /dev/null; then
                setup_macos_daemon_service
            else
                info "macOS daemon service: platform module not loaded"
                info "The daemon can be run manually: rmapd"
            fi
            ;;
        linux)
            if [[ "${PLATFORM_MODULE_LOADED}" == "true" ]] && declare -f setup_linux_daemon_service > /dev/null; then
                setup_linux_daemon_service
            else
                info "Linux daemon service setup not yet implemented."
                info "The daemon can be run manually: rmapd"
                info "See: docs/slices/linux-1-linux-installer.md"
            fi
            ;;
        *)
            info "Daemon service not available for platform: ${PLATFORM}"
            info "The daemon can be run manually: rmapd"
            ;;
    esac
}

# ─────────────────────────────────────────────────────────────────────────────
# Host Integration (stub - implementation in CLAUDE-1/CODEX-1)
# ─────────────────────────────────────────────────────────────────────────────

detect_hosts() {
    if [[ "${BINARY_ONLY}" == "true" ]]; then
        return
    fi

    info ""
    info "Detecting agent hosts..."

    # Claude Code
    if [[ -f "${HOME}/.claude/settings.json" ]]; then
        info "  Claude Code: found (~/.claude/settings.json)"
        DETECTED_CLAUDE=true
    elif [[ -d "${HOME}/.claude" ]]; then
        info "  Claude Code: directory exists (no settings)"
        DETECTED_CLAUDE=true
    else
        DETECTED_CLAUDE=false
    fi

    # Codex
    if [[ -f "${HOME}/.codex/hooks.json" ]] || [[ -d "${HOME}/.codex" ]]; then
        info "  Codex: found"
        DETECTED_CODEX=true
    else
        DETECTED_CODEX=false
    fi

    # Note about integrations
    if [[ "${DETECTED_CLAUDE}" == "true" || "${DETECTED_CODEX}" == "true" ]]; then
        info ""
        info "Host integrations can be installed separately:"
        info "  rmap integrate claude-code"
        info "  rmap integrate codex"
        info ""
        info "Integration commands will be available after HOOK-1 and CLAUDE-1/CODEX-1 are implemented."
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Install Manifest
# ─────────────────────────────────────────────────────────────────────────────

write_manifest() {
    local manifest_path="${CONFIG_DIR}/install-manifest.json"

    info "Writing install manifest to ${manifest_path}..."

    local installed_at
    installed_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    # Build service section based on platform (only if not binary-only)
    local service_section=""
    if [[ "${BINARY_ONLY}" != "true" ]]; then
        case "${PLATFORM}" in
            darwin)
                # macOS: launchd service
                # Path uses variables from lib/macos.sh
                local plist_path="${MACOS_LAUNCHAGENTS_DIR}/${MACOS_PLIST_NAME}"
                service_section=$(cat << SVCEOF
  "service": {
    "type": "launchd",
    "path": "${plist_path}",
    "status": "installed"
  },
SVCEOF
)
                ;;
            linux)
                # Linux: systemd or manual mode (set by setup_linux_daemon_service)
                local service_type="${LINUX_SERVICE_MODE:-manual}"
                local service_path
                if [[ "${service_type}" == "systemd" ]]; then
                    service_path="${HOME}/.config/systemd/user/rmapd.service"
                else
                    service_path="${HOME}/.local/share/rmap/daemon.pid"
                fi
                service_section=$(cat << SVCEOF
  "service": {
    "type": "${service_type}",
    "path": "${service_path}",
    "status": "installed"
  },
SVCEOF
)
                ;;
        esac
    fi

    cat > "${manifest_path}" << EOF
{
  "schema_version": "1",
  "installed_at": "${installed_at}",
  "installer_version": "1.0.0",
  "platform": "${PLATFORM}",
  "arch": "${ARCH}",
  "install_mode": "user",
${service_section}
  "components": {
    "rmap": {
      "path": "${INSTALL_DIR}/rmap",
      "version": "${VERSION}"
    },
    "rmapd": {
      "path": "${INSTALL_DIR}/rmapd",
      "version": "${VERSION}"
    },
    "rgistr": {
      "path": "${INSTALL_DIR}/rgistr",
      "version": "${VERSION}"
    }
  },
  "directories": {
    "config": "${CONFIG_DIR}",
    "data": "${DATA_DIR}",
    "logs": "${LOG_DIR}"
  }
}
EOF
}

# ─────────────────────────────────────────────────────────────────────────────
# Argument Parsing
# ─────────────────────────────────────────────────────────────────────────────

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --version)
                VERSION="$2"
                shift 2
                ;;
            --binary-only)
                BINARY_ONLY=true
                shift
                ;;
            --non-interactive)
                NON_INTERACTIVE=true
                shift
                ;;
            --source)
                BUILD_FROM_SOURCE=true
                shift
                ;;
            --integrate)
                INTEGRATE_HOSTS="$2"
                shift 2
                ;;
            --help|-h)
                echo "repo-graph installer"
                echo ""
                echo "Usage: install.sh [options]"
                echo ""
                echo "Options:"
                echo "  --version <ver>       Install specific version (default: latest)"
                echo "  --binary-only         Skip daemon service and integrations"
                echo "  --non-interactive     Non-interactive mode (no prompts)"
                echo "  --source              Build from source (requires Rust)"
                echo "  --integrate <hosts>   Comma-separated hosts (claude-code,codex)"
                echo "  --help                Show this help"
                echo ""
                echo "Environment variables:"
                echo "  RMAP_VERSION          Install specific version"
                echo "  RMAP_INSTALL_DIR      Install directory (default: ~/.local/bin)"
                echo "  RMAP_BINARY_ONLY      Set to 1 for binary-only install"
                echo "  RMAP_NON_INTERACTIVE  Set to 1 for non-interactive mode"
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                ;;
        esac
    done

    # Apply environment variables
    VERSION="${VERSION:-${RMAP_VERSION:-latest}}"
    INSTALL_DIR="${RMAP_INSTALL_DIR:-${DEFAULT_INSTALL_DIR}}"

    if [[ "${RMAP_BINARY_ONLY:-}" == "1" ]]; then
        BINARY_ONLY=true
    fi

    if [[ "${RMAP_NON_INTERACTIVE:-}" == "1" ]]; then
        NON_INTERACTIVE=true
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

main() {
    echo ""
    echo "repo-graph installer"
    echo "===================="
    echo ""

    parse_args "$@"

    detect_platform
    source_platform_module
    detect_toolchains
    resolve_version

    echo ""

    if [[ "${BUILD_FROM_SOURCE}" == "true" ]]; then
        build_from_source
    else
        download_binary
    fi

    if [[ "${BINARY_ONLY}" != "true" ]]; then
        create_directories
        # INSTALL-ROBUSTNESS-2 (B): daemon-start is best-effort for REACHING the final
        # summary. A genuine failure sets DAEMON_OUTCOME=failed and prints an actionable
        # block (socket path + log) at the point of failure; `|| true` stops `set -e` from
        # aborting BEFORE the summary renders the started/already-running/failed verdict.
        # DAEMON_OUTCOME is a global set on every path, so the outcome survives `|| true`.
        # The pre-slice failure signal is preserved: main still exits 1 on `failed` AFTER
        # the report (see end of main). started/already-running return 0 → `|| true` no-op.
        setup_daemon_service || true  # also sets LINUX_SERVICE_MODE for write_manifest
        write_manifest
        detect_hosts
    fi

    setup_path

    echo ""
    echo "===================="
    # INSTALL-ROBUSTNESS-2 (B): the binaries install independently of the daemon
    # service, so the banner must not overclaim when the daemon failed to start. The
    # daemon-failure block above already gave the actionable detail; here we qualify the
    # headline so "complete" is not read as "everything is healthy".
    if [[ "${BINARY_ONLY}" != "true" && "${DAEMON_OUTCOME}" == "failed" ]]; then
        echo "Installation complete — binaries installed; daemon service NOT running (see above)"
    else
        echo "Installation complete"
    fi
    echo ""
    echo "  CLI:     ${INSTALL_DIR}/rmap"
    echo "  Daemon:  ${INSTALL_DIR}/rmapd"
    echo "  Version: ${VERSION}"
    # INSTALL-ROBUSTNESS-2 (B): state which daemon-start case occurred — started /
    # already running / failed. The socket probe (daemon_socket_answers) is the arbiter,
    # so this line NEVER says "failed" while the socket answers. A genuine "failed" also
    # self-reported the socket path + daemon log in the block above; main exits nonzero
    # after this summary (see below) so scripted installs still detect it.
    if [[ "${BINARY_ONLY}" != "true" && -n "${DAEMON_OUTCOME}" ]]; then
        echo "  Service: daemon ${DAEMON_OUTCOME}"
    fi
    echo ""
    echo "Quick start:"
    echo "  rmap --help          # Show available commands"
    echo "  rmapd                # Run daemon"
    echo "  rmap index <repo>    # Index a repository"
    echo ""

    if [[ "${BINARY_ONLY}" != "true" ]]; then
        echo "Configuration: ${CONFIG_DIR}"
        echo ""
    fi

    echo "Uninstall:"
    echo "  rm ${INSTALL_DIR}/rmap ${INSTALL_DIR}/rmapd ${INSTALL_DIR}/rgistr"
    if [[ "${BINARY_ONLY}" != "true" ]]; then
        echo "  rm -rf ${CONFIG_DIR}"
        echo "  rm -rf ${DATA_DIR}"
    fi
    echo ""

    # INSTALL-ROBUSTNESS-2 (B): the daemon-start verdict was rendered honestly in the
    # summary above (never "failed" while the socket answers). Preserve the pre-slice
    # failure signal — a genuine daemon-start failure exits nonzero AFTER the full report
    # + actionable block, so scripted installs still detect it. Binaries install
    # regardless; started / already running exit 0.
    if [[ "${BINARY_ONLY}" != "true" && "${DAEMON_OUTCOME}" == "failed" ]]; then
        exit 1
    fi
}

main "$@"
