#!/bin/bash
# repo-graph installer template
#
# THIS IS A SOURCE TEMPLATE. Do not run directly via curl|bash.
# The production installer is generated by build-installer.sh and published
# as a release asset.
#
# Production usage:
#   curl -fsSL https://github.com/andreirx/repo-graph/releases/latest/download/install.sh | bash
#
# Development usage (from checkout):
#   ./scripts/install.template.sh
#
# Options (via environment variables):
#   RMAP_VERSION=0.1.0      # Install specific version (default: latest)
#   RMAP_INSTALL_DIR=~/.local/bin  # Install directory
#   RMAP_BINARY_ONLY=1      # Skip daemon service and integrations
#   RMAP_NON_INTERACTIVE=1  # Non-interactive mode (no prompts)
#
# Options (via command line):
#   --version <ver>         # Install specific version
#   --binary-only           # Skip daemon service and integrations
#   --non-interactive       # Non-interactive mode
#   --integrate <hosts>     # Comma-separated hosts to integrate (claude-code,codex)
#   --source               # Build from source (requires Rust toolchain)
#
# See: docs/slices/dist-1-distribution-install-contract.md
#      docs/slices/rel-1-release-pipeline.md

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Script Location Detection
# ─────────────────────────────────────────────────────────────────────────────

# Detect script directory. Empty if running via curl|bash (bundled mode).
if [[ -n "${BASH_SOURCE[0]:-}" ]] && [[ -f "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    SCRIPT_DIR=""
fi

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

# GitHub repository
REPO_OWNER="${RMAP_REPO_OWNER:-andreirx}"
REPO_NAME="repo-graph"
RELEASES_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases"
DOWNLOAD_BASE="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download"

# Default install directory (user-local, no sudo required)
DEFAULT_INSTALL_DIR="${HOME}/.local/bin"

# Platform-specific paths and constants
# These are fallbacks for bundled mode (curl|bash). In modular mode,
# lib/macos.sh or lib/linux.sh may override these.
if [[ "$(uname -s)" == "Darwin" ]]; then
    CONFIG_DIR="${HOME}/Library/Application Support/repo-graph"
    DATA_DIR="${HOME}/Library/Application Support/repo-graph"
    LOG_DIR="${HOME}/Library/Logs/repo-graph"
    # launchd constants (must match lib/macos.sh)
    MACOS_LAUNCHAGENTS_DIR="${HOME}/Library/LaunchAgents"
    MACOS_SERVICE_LABEL="com.repo-graph.rmapd"
    MACOS_PLIST_NAME="${MACOS_SERVICE_LABEL}.plist"
else
    CONFIG_DIR="${HOME}/.config/rmap"
    DATA_DIR="${HOME}/.local/share/rmap"
    LOG_DIR="${HOME}/.local/share/rmap/logs"
    # systemd constants
    LINUX_SERVICE_MODE="${LINUX_SERVICE_MODE:-manual}"
fi

# State
VERSION=""
INSTALL_DIR=""
BINARY_ONLY="${RMAP_BINARY_ONLY:-false}"
NON_INTERACTIVE="${RMAP_NON_INTERACTIVE:-false}"
BUILD_FROM_SOURCE=false
INTEGRATE_HOSTS=""

# ─────────────────────────────────────────────────────────────────────────────
# Utilities
# ─────────────────────────────────────────────────────────────────────────────

info() {
    echo "[info] $*"
}

warn() {
    echo "[warn] $*" >&2
}

error() {
    echo "[error] $*" >&2
    exit 1
}

confirm() {
    local prompt="$1"
    local default="${2:-n}"

    if [[ "${NON_INTERACTIVE}" == "true" ]]; then
        return 0
    fi

    if [[ "${default}" == "y" ]]; then
        read -r -p "${prompt} [Y/n]: " response
        [[ -z "${response}" || "${response}" =~ ^[Yy] ]]
    else
        read -r -p "${prompt} [y/N]: " response
        [[ "${response}" =~ ^[Yy] ]]
    fi
}

command_exists() {
    command -v "$1" &> /dev/null
}

# __INJECT_PLATFORM_MODULES__

# ─────────────────────────────────────────────────────────────────────────────
# Platform Detection
# ─────────────────────────────────────────────────────────────────────────────

detect_platform() {
    local os arch

    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    arch="$(uname -m)"

    # Normalize architecture
    case "${arch}" in
        x86_64|amd64)
            arch="x86_64"
            ;;
        arm64|aarch64)
            arch="aarch64"
            ;;
        *)
            error "Unsupported architecture: ${arch}"
            ;;
    esac

    # Normalize platform
    case "${os}" in
        darwin)
            PLATFORM="darwin"
            ;;
        linux)
            PLATFORM="linux"
            ;;
        *)
            error "Unsupported platform: ${os}"
            ;;
    esac

    ARCH="${arch}"
    info "Detected platform: ${PLATFORM}-${ARCH}"
}

# Source platform-specific module after platform detection.
# Called from main() after detect_platform().
#
# In modular mode (run from checkout): sources lib/macos.sh or lib/linux.sh
# In bundled mode (generated installer): libs are already inlined
source_platform_module() {
    # Check if platform functions are already defined (bundled installer).
    # This check must come FIRST because the bundled installer may be run
    # from a file path (bash install.sh), not just piped (curl|bash).
    if declare -f setup_macos_daemon_service > /dev/null 2>&1 || \
       declare -f setup_linux_daemon_service > /dev/null 2>&1; then
        PLATFORM_MODULE_LOADED=true
        return
    fi

    # Modular mode: try to source platform modules from lib/
    if [[ -z "${SCRIPT_DIR}" ]]; then
        # No SCRIPT_DIR and no bundled functions - truly headless mode
        PLATFORM_MODULE_LOADED=false
        return
    fi

    local lib_dir="${SCRIPT_DIR}/lib"

    case "${PLATFORM}" in
        darwin)
            if [[ -f "${lib_dir}/macos.sh" ]]; then
                source "${lib_dir}/macos.sh"
                PLATFORM_MODULE_LOADED=true
            else
                PLATFORM_MODULE_LOADED=false
            fi
            ;;
        linux)
            if [[ -f "${lib_dir}/linux.sh" ]]; then
                source "${lib_dir}/linux.sh"
                PLATFORM_MODULE_LOADED=true
            else
                PLATFORM_MODULE_LOADED=false
            fi
            ;;
        *)
            PLATFORM_MODULE_LOADED=false
            ;;
    esac
}

# ─────────────────────────────────────────────────────────────────────────────
# Toolchain Detection (informational only, not required for binary install)
# ─────────────────────────────────────────────────────────────────────────────

detect_toolchains() {
    info "Detecting toolchains..."

    # Rust (required for source build)
    if command_exists rustc; then
        local rust_version
        rust_version="$(rustc --version 2>/dev/null | awk '{print $2}')"
        info "  Rust: ${rust_version}"
        RUST_AVAILABLE=true
    else
        info "  Rust: not found"
        RUST_AVAILABLE=false
    fi

    # Cargo
    if command_exists cargo; then
        local cargo_version
        cargo_version="$(cargo --version 2>/dev/null | awk '{print $2}')"
        info "  Cargo: ${cargo_version}"
    fi

    # Node.js (not required for rmap, informational only)
    if command_exists node; then
        local node_version
        node_version="$(node --version 2>/dev/null)"
        info "  Node.js: ${node_version}"
    else
        info "  Node.js: not found (not required)"
    fi

    # npm (not required for rmap, informational only)
    if command_exists npm; then
        local npm_version
        npm_version="$(npm --version 2>/dev/null)"
        info "  npm: ${npm_version}"
    else
        info "  npm: not found (not required)"
    fi

    # Note about requirements
    if [[ "${BUILD_FROM_SOURCE}" == "true" && "${RUST_AVAILABLE}" != "true" ]]; then
        error "Source build requested but Rust toolchain not found. Install from: https://rustup.rs"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Version Resolution
# ─────────────────────────────────────────────────────────────────────────────

resolve_version() {
    if [[ -n "${VERSION}" && "${VERSION}" != "latest" ]]; then
        info "Using specified version: ${VERSION}"
        return
    fi

    info "Fetching latest version..."

    if ! command_exists curl; then
        error "curl is required but not found"
    fi

    # Network step: resolve the latest release tag from the GitHub API.
    #
    # Observability + fail-fast (the reported silent-hang fix):
    #   - Log the exact URL before the request so a stall here is attributable.
    #   - Bound the request with --connect-timeout/--max-time so an unreachable,
    #     IPv6-stalled, proxied, or rate-limited api.github.com FAILS in seconds
    #     instead of hanging forever (this curl previously had NO timeout).
    #   - The curl is split out of the parse pipeline so its exit code is
    #     observable: a "curl | grep | sed" pipeline assigned via `local` masks
    #     curl's exit status, which is exactly why the failure was invisible.
    #     The resolution logic (URL, tag_name parse, 'v'-prefix strip) is
    #     unchanged — only the plumbing that exposes the exit code differs.
    #   - 2>/dev/null is dropped so curl's own -S error line (e.g. "curl: (28)
    #     ...") surfaces alongside our actionable message.
    # NOTE: api.github.com is the ONLY host this step uses; the binary download
    # (download_binary) uses github.com. An error here therefore points at the
    # API host specifically, which distinguishes a rate limit from no connectivity.
    info "  GET ${RELEASES_URL}/latest"

    local api_response curl_exit
    api_response="$(curl -fsSL --connect-timeout 10 --max-time 30 "${RELEASES_URL}/latest")" && curl_exit=0 || curl_exit=$?

    if [[ "${curl_exit}" -ne 0 ]]; then
        error "Could not reach api.github.com (curl exit ${curl_exit}) — likely a network/proxy issue or the GitHub API rate limit. This step is the ONLY one that contacts api.github.com (the binary download uses github.com), so this points at the API host specifically. Retry, or pin the version to skip the API lookup: RMAP_VERSION=<ver> curl -fsSL <install-url> | bash"
    fi

    # Parse the resolved tag from the API response (logic unchanged).
    local latest_tag
    latest_tag="$(printf '%s' "${api_response}" | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')"

    if [[ -z "${latest_tag}" ]]; then
        error "Could not determine latest version (api.github.com was reachable but the response had no tag_name). Specify version with --version or RMAP_VERSION"
    fi

    # Remove 'v' prefix
    VERSION="${latest_tag#v}"
    info "Latest version: ${VERSION}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Download and Verify
# ─────────────────────────────────────────────────────────────────────────────

download_binary() {
    local artifact="rmap-${VERSION}-${PLATFORM}-${ARCH}.tar.gz"
    local download_url="${DOWNLOAD_BASE}/v${VERSION}/${artifact}"
    local checksum_url="${download_url}.sha256"

    local tmp_dir
    tmp_dir="$(mktemp -d)"
    trap "rm -rf '${tmp_dir}'" EXIT

    # Network step: download the release tarball + checksum from github.com
    # (NOT api.github.com — that host is only used by resolve_version). Log the
    # exact URL before each request and capture each curl exit code so a failure
    # names the URL + exit code instead of failing silently.
    #
    # Timeouts: --connect-timeout 10 fails fast if the connection cannot be
    # established (the stall failure mode). The tarball is a multi-MB binary, so
    # it gets a generous --max-time 600 (10 min) backstop — large enough not to
    # abort a legitimately slow-but-progressing download, small enough that a
    # wedged transfer cannot hang forever. The checksum is a few bytes, so it
    # reuses the tight --max-time 30 (same as the API call).
    # (A future refinement could swap the tarball's fixed --max-time for
    # --speed-limit/--speed-time to abort only on a true mid-transfer stall; that
    # is out of scope for this logging/timeout slice.)
    info "Downloading ${artifact}..."
    info "  GET ${download_url}"
    local dl_exit
    curl -fsSL --connect-timeout 10 --max-time 600 -o "${tmp_dir}/${artifact}" "${download_url}" && dl_exit=0 || dl_exit=$?
    if [[ "${dl_exit}" -ne 0 ]]; then
        error "Failed to download ${artifact} (curl exit ${dl_exit}) from ${download_url}"
    fi

    info "Downloading checksum..."
    info "  GET ${checksum_url}"
    local sum_exit
    curl -fsSL --connect-timeout 10 --max-time 30 -o "${tmp_dir}/${artifact}.sha256" "${checksum_url}" && sum_exit=0 || sum_exit=$?
    if [[ "${sum_exit}" -ne 0 ]]; then
        error "Failed to download checksum (curl exit ${sum_exit}) from ${checksum_url}"
    fi

    info "Verifying checksum..."
    cd "${tmp_dir}"
    if command_exists shasum; then
        if ! shasum -a 256 -c "${artifact}.sha256"; then
            error "Checksum verification failed!"
        fi
    elif command_exists sha256sum; then
        if ! sha256sum -c "${artifact}.sha256"; then
            error "Checksum verification failed!"
        fi
    else
        warn "No checksum tool found (shasum or sha256sum). Skipping verification."
    fi

    info "Extracting archive..."
    tar -xzf "${artifact}"

    # Move binaries to install location
    EXTRACTED_DIR="rmap-${VERSION}-${PLATFORM}-${ARCH}"
    if [[ ! -f "${EXTRACTED_DIR}/rmap" ]]; then
        error "CLI binary (rmap) not found in archive"
    fi
    if [[ ! -f "${EXTRACTED_DIR}/rmapd" ]]; then
        error "Daemon binary (rmapd) not found in archive"
    fi
    if [[ ! -f "${EXTRACTED_DIR}/rgistr" ]]; then
        error "rgistr binary not found in archive"
    fi

    # Create install directory if needed
    mkdir -p "${INSTALL_DIR}"

    info "Installing CLI to ${INSTALL_DIR}/rmap..."
    install -m 755 "${EXTRACTED_DIR}/rmap" "${INSTALL_DIR}/rmap"

    info "Installing daemon to ${INSTALL_DIR}/rmapd..."
    install -m 755 "${EXTRACTED_DIR}/rmapd" "${INSTALL_DIR}/rmapd"

    info "Installing rgistr to ${INSTALL_DIR}/rgistr..."
    install -m 755 "${EXTRACTED_DIR}/rgistr" "${INSTALL_DIR}/rgistr"

    # Verify installation
    if ! "${INSTALL_DIR}/rmap" --version > /dev/null 2>&1; then
        # On macOS, Gatekeeper may block unsigned binaries
        if [[ "${PLATFORM}" == "darwin" ]]; then
            warn ""
            warn "macOS Gatekeeper may have blocked the binaries."
            warn "To allow, run:"
            warn "  xattr -d com.apple.quarantine ${INSTALL_DIR}/rmap"
            warn "  xattr -d com.apple.quarantine ${INSTALL_DIR}/rmapd"
            warn "  xattr -d com.apple.quarantine ${INSTALL_DIR}/rgistr"
            warn ""
            warn "Or: System Preferences -> Security & Privacy -> Allow"
            warn ""

            if confirm "Run xattr commands now?"; then
                xattr -d com.apple.quarantine "${INSTALL_DIR}/rmap" 2>/dev/null || true
                xattr -d com.apple.quarantine "${INSTALL_DIR}/rmapd" 2>/dev/null || true
                xattr -d com.apple.quarantine "${INSTALL_DIR}/rgistr" 2>/dev/null || true

                if "${INSTALL_DIR}/rmap" --version > /dev/null 2>&1; then
                    info "Binaries unblocked successfully"
                else
                    error "Binary verification still failed after unblocking"
                fi
            fi
        else
            error "Binary verification failed"
        fi
    fi

    local installed_version
    installed_version="$("${INSTALL_DIR}/rmap" --version 2>/dev/null | head -1)"
    info "Installed: ${installed_version}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Source Build
# ─────────────────────────────────────────────────────────────────────────────

build_from_source() {
    info "Building from source..."

    if [[ "${RUST_AVAILABLE}" != "true" ]]; then
        error "Rust toolchain required for source build. Install from: https://rustup.rs"
    fi

    local tmp_dir
    tmp_dir="$(mktemp -d)"
    trap "rm -rf '${tmp_dir}'" EXIT

    info "Cloning repository..."
    if ! command_exists git; then
        error "git is required for source build"
    fi

    git clone --depth 1 --branch "v${VERSION}" \
        "https://github.com/${REPO_OWNER}/${REPO_NAME}.git" \
        "${tmp_dir}/repo-graph"

    cd "${tmp_dir}/repo-graph/rust"

    info "Building release binaries..."
    cargo build --release -p repo-graph-rgr -p rmapd

    # Install Rust binaries
    mkdir -p "${INSTALL_DIR}"
    install -m 755 "target/release/rmap" "${INSTALL_DIR}/rmap"
    install -m 755 "target/release/rmapd" "${INSTALL_DIR}/rmapd"

    # Build rgistr (required - rgistr is a first-class release component)
    if ! command_exists node || ! command_exists npm; then
        error "Node.js and npm required for source build (rgistr is a first-class component)"
    fi

    info "Building rgistr..."
    cd "${tmp_dir}/repo-graph/tools/rgistr"
    npm ci
    npm run bundle
    ./scripts/build-sea.sh "${PLATFORM}" "${ARCH}"
    install -m 755 "build/rgistr-${PLATFORM}-${ARCH}" "${INSTALL_DIR}/rgistr"

    local installed_version
    installed_version="$("${INSTALL_DIR}/rmap" --version 2>/dev/null | head -1)"
    info "Installed: ${installed_version}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Directory Setup
# ─────────────────────────────────────────────────────────────────────────────

create_directories() {
    info "Creating directories..."

    mkdir -p "${CONFIG_DIR}"
    mkdir -p "${DATA_DIR}/databases"
    mkdir -p "${DATA_DIR}/sessions"
    mkdir -p "${LOG_DIR}"

    # Set permissions
    chmod 700 "${CONFIG_DIR}"
    chmod 700 "${DATA_DIR}"
    chmod 700 "${LOG_DIR}"

    info "  Config: ${CONFIG_DIR}"
    info "  Data: ${DATA_DIR}"
    info "  Logs: ${LOG_DIR}"
}

# ─────────────────────────────────────────────────────────────────────────────
# PATH Setup
# ─────────────────────────────────────────────────────────────────────────────

setup_path() {
    # Check if install dir is in PATH
    if [[ ":${PATH}:" == *":${INSTALL_DIR}:"* ]]; then
        info "${INSTALL_DIR} is already in PATH"
        return
    fi

    info "${INSTALL_DIR} is not in PATH"

    if [[ "${NON_INTERACTIVE}" == "true" ]]; then
        warn "Add to PATH manually: export PATH=\"${INSTALL_DIR}:\$PATH\""
        return
    fi

    # Detect shell profile
    local shell_profile=""
    local shell_name=""

    case "${SHELL}" in
        */zsh)
            shell_name="zsh"
            shell_profile="${HOME}/.zshrc"
            ;;
        */bash)
            shell_name="bash"
            if [[ -f "${HOME}/.bash_profile" ]]; then
                shell_profile="${HOME}/.bash_profile"
            else
                shell_profile="${HOME}/.bashrc"
            fi
            ;;
        *)
            shell_profile="${HOME}/.profile"
            ;;
    esac

    if confirm "Add ${INSTALL_DIR} to PATH in ${shell_profile}?"; then
        local path_line="export PATH=\"${INSTALL_DIR}:\$PATH\""

        # Check if already added
        if grep -q "${INSTALL_DIR}" "${shell_profile}" 2>/dev/null; then
            info "PATH entry already exists in ${shell_profile}"
        else
            echo "" >> "${shell_profile}"
            echo "# repo-graph" >> "${shell_profile}"
            echo "${path_line}" >> "${shell_profile}"
            info "Added to ${shell_profile}"
            info ""
            info "Run 'source ${shell_profile}' or start a new terminal to update PATH"
        fi
    else
        warn "Add to PATH manually: export PATH=\"${INSTALL_DIR}:\$PATH\""
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Daemon Service
# ─────────────────────────────────────────────────────────────────────────────

setup_daemon_service() {
    if [[ "${BINARY_ONLY}" == "true" ]]; then
        info "Skipping daemon service (--binary-only)"
        return
    fi

    info ""

    # Dispatch to platform-specific module
    case "${PLATFORM}" in
        darwin)
            if [[ "${PLATFORM_MODULE_LOADED}" == "true" ]] && declare -f setup_macos_daemon_service > /dev/null; then
                setup_macos_daemon_service
            else
                info "macOS daemon service: platform module not loaded"
                info "The daemon can be run manually: rmapd"
            fi
            ;;
        linux)
            if [[ "${PLATFORM_MODULE_LOADED}" == "true" ]] && declare -f setup_linux_daemon_service > /dev/null; then
                setup_linux_daemon_service
            else
                info "Linux daemon service setup not yet implemented."
                info "The daemon can be run manually: rmapd"
                info "See: docs/slices/linux-1-linux-installer.md"
            fi
            ;;
        *)
            info "Daemon service not available for platform: ${PLATFORM}"
            info "The daemon can be run manually: rmapd"
            ;;
    esac
}

# ─────────────────────────────────────────────────────────────────────────────
# Host Integration (stub - implementation in CLAUDE-1/CODEX-1)
# ─────────────────────────────────────────────────────────────────────────────

detect_hosts() {
    if [[ "${BINARY_ONLY}" == "true" ]]; then
        return
    fi

    info ""
    info "Detecting agent hosts..."

    # Claude Code
    if [[ -f "${HOME}/.claude/settings.json" ]]; then
        info "  Claude Code: found (~/.claude/settings.json)"
        DETECTED_CLAUDE=true
    elif [[ -d "${HOME}/.claude" ]]; then
        info "  Claude Code: directory exists (no settings)"
        DETECTED_CLAUDE=true
    else
        DETECTED_CLAUDE=false
    fi

    # Codex
    if [[ -f "${HOME}/.codex/hooks.json" ]] || [[ -d "${HOME}/.codex" ]]; then
        info "  Codex: found"
        DETECTED_CODEX=true
    else
        DETECTED_CODEX=false
    fi

    # Note about integrations
    if [[ "${DETECTED_CLAUDE}" == "true" || "${DETECTED_CODEX}" == "true" ]]; then
        info ""
        info "Host integrations can be installed separately:"
        info "  rmap integrate claude-code"
        info "  rmap integrate codex"
        info ""
        info "Integration commands will be available after HOOK-1 and CLAUDE-1/CODEX-1 are implemented."
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Install Manifest
# ─────────────────────────────────────────────────────────────────────────────

write_manifest() {
    local manifest_path="${CONFIG_DIR}/install-manifest.json"

    info "Writing install manifest to ${manifest_path}..."

    local installed_at
    installed_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    # Build service section based on platform (only if not binary-only)
    local service_section=""
    if [[ "${BINARY_ONLY}" != "true" ]]; then
        case "${PLATFORM}" in
            darwin)
                # macOS: launchd service
                # Path uses variables from lib/macos.sh
                local plist_path="${MACOS_LAUNCHAGENTS_DIR}/${MACOS_PLIST_NAME}"
                service_section=$(cat << SVCEOF
  "service": {
    "type": "launchd",
    "path": "${plist_path}",
    "status": "installed"
  },
SVCEOF
)
                ;;
            linux)
                # Linux: systemd or manual mode (set by setup_linux_daemon_service)
                local service_type="${LINUX_SERVICE_MODE:-manual}"
                local service_path
                if [[ "${service_type}" == "systemd" ]]; then
                    service_path="${HOME}/.config/systemd/user/rmapd.service"
                else
                    service_path="${HOME}/.local/share/rmap/daemon.pid"
                fi
                service_section=$(cat << SVCEOF
  "service": {
    "type": "${service_type}",
    "path": "${service_path}",
    "status": "installed"
  },
SVCEOF
)
                ;;
        esac
    fi

    cat > "${manifest_path}" << EOF
{
  "schema_version": "1",
  "installed_at": "${installed_at}",
  "installer_version": "1.0.0",
  "platform": "${PLATFORM}",
  "arch": "${ARCH}",
  "install_mode": "user",
${service_section}
  "components": {
    "rmap": {
      "path": "${INSTALL_DIR}/rmap",
      "version": "${VERSION}"
    },
    "rmapd": {
      "path": "${INSTALL_DIR}/rmapd",
      "version": "${VERSION}"
    },
    "rgistr": {
      "path": "${INSTALL_DIR}/rgistr",
      "version": "${VERSION}"
    }
  },
  "directories": {
    "config": "${CONFIG_DIR}",
    "data": "${DATA_DIR}",
    "logs": "${LOG_DIR}"
  }
}
EOF
}

# ─────────────────────────────────────────────────────────────────────────────
# Argument Parsing
# ─────────────────────────────────────────────────────────────────────────────

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --version)
                VERSION="$2"
                shift 2
                ;;
            --binary-only)
                BINARY_ONLY=true
                shift
                ;;
            --non-interactive)
                NON_INTERACTIVE=true
                shift
                ;;
            --source)
                BUILD_FROM_SOURCE=true
                shift
                ;;
            --integrate)
                INTEGRATE_HOSTS="$2"
                shift 2
                ;;
            --help|-h)
                echo "repo-graph installer"
                echo ""
                echo "Usage: install.sh [options]"
                echo ""
                echo "Options:"
                echo "  --version <ver>       Install specific version (default: latest)"
                echo "  --binary-only         Skip daemon service and integrations"
                echo "  --non-interactive     Non-interactive mode (no prompts)"
                echo "  --source              Build from source (requires Rust)"
                echo "  --integrate <hosts>   Comma-separated hosts (claude-code,codex)"
                echo "  --help                Show this help"
                echo ""
                echo "Environment variables:"
                echo "  RMAP_VERSION          Install specific version"
                echo "  RMAP_INSTALL_DIR      Install directory (default: ~/.local/bin)"
                echo "  RMAP_BINARY_ONLY      Set to 1 for binary-only install"
                echo "  RMAP_NON_INTERACTIVE  Set to 1 for non-interactive mode"
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                ;;
        esac
    done

    # Apply environment variables
    VERSION="${VERSION:-${RMAP_VERSION:-latest}}"
    INSTALL_DIR="${RMAP_INSTALL_DIR:-${DEFAULT_INSTALL_DIR}}"

    if [[ "${RMAP_BINARY_ONLY:-}" == "1" ]]; then
        BINARY_ONLY=true
    fi

    if [[ "${RMAP_NON_INTERACTIVE:-}" == "1" ]]; then
        NON_INTERACTIVE=true
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

main() {
    echo ""
    echo "repo-graph installer"
    echo "===================="
    echo ""

    parse_args "$@"

    detect_platform
    source_platform_module
    detect_toolchains
    resolve_version

    echo ""

    if [[ "${BUILD_FROM_SOURCE}" == "true" ]]; then
        build_from_source
    else
        download_binary
    fi

    if [[ "${BINARY_ONLY}" != "true" ]]; then
        create_directories
        setup_daemon_service  # Must run before write_manifest (sets LINUX_SERVICE_MODE)
        write_manifest
        detect_hosts
    fi

    setup_path

    echo ""
    echo "===================="
    echo "Installation complete"
    echo ""
    echo "  CLI:     ${INSTALL_DIR}/rmap"
    echo "  Daemon:  ${INSTALL_DIR}/rmapd"
    echo "  Version: ${VERSION}"
    echo ""
    echo "Quick start:"
    echo "  rmap --help          # Show available commands"
    echo "  rmapd                # Run daemon"
    echo "  rmap index <repo>    # Index a repository"
    echo ""

    if [[ "${BINARY_ONLY}" != "true" ]]; then
        echo "Configuration: ${CONFIG_DIR}"
        echo ""
    fi

    echo "Uninstall:"
    echo "  rm ${INSTALL_DIR}/rmap ${INSTALL_DIR}/rmapd ${INSTALL_DIR}/rgistr"
    if [[ "${BINARY_ONLY}" != "true" ]]; then
        echo "  rm -rf ${CONFIG_DIR}"
        echo "  rm -rf ${DATA_DIR}"
    fi
    echo ""
}

main "$@"
