//! COMPLEXITY-SCOPE-1 (RG-REQ-001-L08) reproducing test — a file's `is_generated`
//! flag is its first-lines banner, persisted at index time and carried across a
//! no-change refresh.
//!
//! Before this slice every construction site wrote `is_generated: false`, so the
//! flag was dead on every store (RC-9). The indexer now runs a content sniff on the
//! first eight lines: a machine-authored banner marks the file, a hand-written file
//! that merely mentions code generation does not, and a banner below the eighth line
//! does not. The copy-forward path carries the STORED flag, so a no-change refresh —
//! whose `upsert_files` ON CONFLICT would otherwise reset the flag — preserves it.
//!
//! Drives the REAL write path (`compose::index_into_storage` / `refresh_into_storage`)
//! and reads back through the `FileCatalogPort`, never raw SQL.

use repo_graph_indexer::storage_port::{FileCatalogPort, TrackedFile};
use repo_graph_repo_index::compose::{index_into_storage, refresh_into_storage, ComposeOptions};
use repo_graph_storage::StorageConnection;
use std::fs;

/// Fixture files, one per case (the marker literals live only inside these strings,
/// never in this file's own head — so the product indexing its own tree flags nothing):
/// - `src/parser.c`   — tree-sitter banner on line 1 → GENERATED
/// - `src/grammar.cpp` — Bison banner on line 1 → GENERATED
/// - `src/types.d.ts` — wrangler `DO NOT EDIT` on line 1 → GENERATED
/// - `src/block.cc`   — hand-written leveldb-shape header mentioning generation on line 5 → NOT
/// - `src/late.c`     — the generic marker only on line 9 → NOT (outside the window)
fn write_fixture(dir: &std::path::Path) {
    fs::create_dir_all(dir.join("src")).unwrap();

    fs::write(
        dir.join("src/parser.c"),
        "/* Automatically @generated by tree-sitter v0.25.10 */\n\
         int ts_lex(void) { return 0; }\n",
    )
    .unwrap();

    fs::write(
        dir.join("src/grammar.cpp"),
        "/* A Bison parser, made by GNU Bison 3.8.2.  */\n\
         int yyparse(void) { return 0; }\n",
    )
    .unwrap();

    fs::write(
        dir.join("src/types.d.ts"),
        "// Generated by wrangler. DO NOT EDIT.\n\
         export interface Env { KEY: string }\n",
    )
    .unwrap();

    // Hand-written leveldb `table/block.cc` shape: the word "generated" appears in a
    // prose comment on line 5, but no frozen marker does — must stay unflagged.
    fs::write(
        dir.join("src/block.cc"),
        "// Copyright (c) 2011 The LevelDB Authors. All rights reserved.\n\
         // Use of this source code is governed by a BSD-style license that can be\n\
         // found in the LICENSE file. See the AUTHORS file for names of contributors.\n\
         //\n\
         // Decodes the blocks generated by block_builder.cc.\n\
         \n\
         int decode() { return 0; }\n",
    )
    .unwrap();

    // The generic marker appears ONLY on line 9 — outside the first-eight-lines window.
    fs::write(
        dir.join("src/late.c"),
        "// line 1\n// line 2\n// line 3\n// line 4\n// line 5\n// line 6\n// line 7\n// line 8\n\
         // @generated late\nint f(void) { return 0; }\n",
    )
    .unwrap();
}

fn generated_of(files: &[TrackedFile], path: &str) -> bool {
    files
        .iter()
        .find(|f| f.path == path)
        .unwrap_or_else(|| panic!("file {path} not tracked; tracked = {files:?}"))
        .is_generated
}

#[test]
fn generated_flag_is_persisted_from_a_first_lines_marker() {
    let dir = tempfile::tempdir().unwrap();
    write_fixture(dir.path());

    let mut storage = StorageConnection::open_in_memory().unwrap();
    index_into_storage(dir.path(), &mut storage, "fx", &ComposeOptions::default()).unwrap();

    let files = FileCatalogPort::get_files_by_repo(&storage, "fx").unwrap();

    assert!(
        generated_of(&files, "src/parser.c"),
        "tree-sitter banner on line 1 → is_generated TRUE",
    );
    assert!(
        generated_of(&files, "src/grammar.cpp"),
        "Bison banner on line 1 → is_generated TRUE",
    );
    assert!(
        generated_of(&files, "src/types.d.ts"),
        "wrangler DO NOT EDIT banner on line 1 → is_generated TRUE",
    );

    // The count of generated files read back through the port is exactly 3.
    let generated_count = files.iter().filter(|f| f.is_generated).count();
    assert_eq!(
        generated_count, 3,
        "exactly the three banner-carrying files are generated; tracked = {files:?}",
    );
}

#[test]
fn hand_written_files_stay_unflagged() {
    let dir = tempfile::tempdir().unwrap();
    write_fixture(dir.path());

    let mut storage = StorageConnection::open_in_memory().unwrap();
    index_into_storage(dir.path(), &mut storage, "fx", &ComposeOptions::default()).unwrap();

    let files = FileCatalogPort::get_files_by_repo(&storage, "fx").unwrap();

    assert!(
        !generated_of(&files, "src/block.cc"),
        "a hand-written header mentioning generation on line 5 must stay unflagged",
    );
    assert!(
        !generated_of(&files, "src/late.c"),
        "a marker on line 9 is outside the window → must stay unflagged",
    );
}

#[test]
fn is_generated_survives_no_change_refresh() {
    let dir = tempfile::tempdir().unwrap();
    write_fixture(dir.path());

    let mut storage = StorageConnection::open_in_memory().unwrap();
    index_into_storage(dir.path(), &mut storage, "fx", &ComposeOptions::default()).unwrap();
    // No file changes → every file copies forward; the copy-forward path must carry the
    // STORED flag (the ON CONFLICT upsert would otherwise reset it to false).
    refresh_into_storage(dir.path(), &mut storage, "fx", &ComposeOptions::default()).unwrap();

    let files = FileCatalogPort::get_files_by_repo(&storage, "fx").unwrap();

    assert!(
        generated_of(&files, "src/parser.c"),
        "refresh preserves parser.c"
    );
    assert!(
        generated_of(&files, "src/grammar.cpp"),
        "refresh preserves grammar.cpp",
    );
    assert!(
        generated_of(&files, "src/types.d.ts"),
        "refresh preserves types.d.ts",
    );
    assert!(
        !generated_of(&files, "src/block.cc"),
        "refresh keeps the hand-written file unflagged",
    );
    assert!(
        !generated_of(&files, "src/late.c"),
        "refresh keeps the late-marker file unflagged",
    );
    let generated_count = files.iter().filter(|f| f.is_generated).count();
    assert_eq!(
        generated_count, 3,
        "the flag count survives a no-change refresh"
    );
}
